### ISSUE TITLE
Problem with comma splitting docker parameters into several commands

### ISSUE THREAD

**Issue by olegtarasov** [appleboy/ssh-action#10]
You have a comma `,` used to separate multiple commands in a single string. This makes it impossible to run commands which have a comma in their parameters. For example, docker `mount`:

```
--mount type=volume,src=<VOLUME-NAME>,dst=<CONTAINER-PATH>
```

This parameter line is split at commas even though I use multiline YAML format for `script`. Maybe it's better to remove comma altogether and rely exclusively on YAML multiline support.

**Comment by appleboy** [comment]
@olegtarasov I will fix the issue asap.

**Comment by appleboy** [comment]
![Screen Shot 2019-11-21 at 11 11 50 AM](https://user-images.githubusercontent.com/21979/69300989-c9741880-0c4f-11ea-8bc2-c09f719d84df.png)

**Comment by appleboy** [comment]
try the 0.0.5 version https://github.com/appleboy/ssh-action/releases/tag/v0.0.5
