### ISSUE TITLE
command git pull stuck

### ISSUE THREAD

**Issue by ghmus** [appleboy/ssh-action#102]
Trying to execute a .bat file on windows which contains "git pull origin <branch>" keeps the job running forever with no output

**Comment by ShravaniRoy** [comment]
> Trying to execute a .bat file on windows which contains "git pull origin " keeps the job running forever with no output

@ghmus did you find any solution? if yes, I request you to share it here. I have similar issue. bat file doesn't run at all. timeout with success message.

**Comment by ghmus** [comment]
@ShravaniRoy yes i did; the problem was git and ssh-action using the same port 22

**Comment by appleboy** [comment]
See https://github.com/appleboy/ssh-action/issues/232#issuecomment-1506493783
