### ISSUE TITLE
NVM Command not found

### ISSUE THREAD

**Issue by danreale** [appleboy/ssh-action#105]
I am using nvm and pm2 on my digital ocean server. I am trying to restart my pm2 services with this github action but every time I am getting either nvm and pm2 not found.  Any ideas why this would happen?

err: bash: line 1: nvm: command not found

**Comment by appleboy** [comment]
See the reference: https://github.com/appleboy/ssh-action/issues/21#issuecomment-574050424

**Comment by danreale** [comment]
Thank you for pointing me to the reference. That worked!
