### ISSUE TITLE
Passing options to ssh

### ISSUE THREAD

**Issue by jigar1101** [appleboy/ssh-action#11]
Is it possible to pass options to the ssh command? 
I couldn't find it in the documentation.

For example how we pass it via ssh `-o StrictHostKeyChecking=no`

**Comment by appleboy** [comment]
What're the options do you want? The default `StrictHostKeyChecking` value as `no`

**Comment by niecore** [comment]
For instance `-6` for the usage of ipv6

**Comment by oneturkmen** [comment]
@appleboy ^^^^ (ipv6)

**Comment by appleboy** [comment]
@niecore @oneturkmen try the master version for the IPV6 feature.
