### ISSUE TITLE
Could the action fail if some of the commands in the script failed?

### ISSUE THREAD

**Issue by antoniogamiz** [appleboy/ssh-action#112]
Hi, I would like to know if it's possible to cause the action run to fail if some of the commands in the script failed. It would be quite helpful to avoid having to look to the logs to know if something went wrong.

**Comment by h1dden-da3m0n** [comment]
A bit further down in the readme:
![image](https://user-images.githubusercontent.com/33120068/113438131-3ffa5c00-93e8-11eb-98ce-b19369edaf51.png)
 (unfortunately the readme has no headlines or other anchors to link you to this)

**Comment by appleboy** [comment]
@h1dden-da3m0n We can improve the format of README.

**Comment by h1dden-da3m0n** [comment]
hey @appleboy, I will send you a PR regarding that later. Just wanted to answer ;)

**Comment by antoniogamiz** [comment]
I did not see it, sorry. Thanks for letting me know!! :D
