### ISSUE TITLE
The printed log shows "out: ***". Why does it show "***" instead of the real "out".

### ISSUE THREAD

**Issue by littlecorgi-twk** [appleboy/ssh-action#116]
```
Run appleboy/ssh-action@master
/usr/bin/docker run --name a33c108bc9abd62334a6e9748bece57aa8d2b_ba61c2 --label 8a33c1 --workdir /github/workspace --rm -e JAVA_HOME -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_SCRIPT -e INPUT_PORT -e INPUT_PASSPHRASE -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/CoursejiServer/CoursejiServer":"/github/workspace" 8a33c1:08bc9abd62334a6e9748bece57aa8d2b
======CMD======
whoami
pkill -9 -f "java -jar /***/CoursejiServer/courseji/target/courseji-0.0.1-SNAPSHOT.jar"
nohup java -jar /***/CoursejiServer/courseji/target/courseji-0.0.1-SNAPSHOT.jar > /***/CoursejiServer/courseji.txt &

======END======
out: ***
2021/04/23 16:30:52 Process exited with status 137 from signal KILL
```

The printed log shows "out: ***". Why does it show "***" instead of the real "out".

And why it show the error: "Process exited with status 137 from signal KILL"

**Comment by charnlsxy** [comment]
I also encountered a similar problem. *** I think it is an encrypted string, such as root
`
/usr/bin/docker run --name a33c1b97182f2b552450485e7d299737c5985_98d603 --label 8a33c1 --workdir /github/workspace --rm -e JAVA_HOME -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_DEBUG -e INPUT_SCRIPT_STOP -e INPUT_SCRIPT -e INPUT_PORT -e INPUT_PASSPHRASE -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_ENVS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/deploy-test-spring/deploy-test-spring":"/github/workspace" 8a33c1:b97182f2b552450485e7d299737c5985
======CMD======
cd actions/deploy-test-spring/target
ps -ef | grep deploy-test-spring.jar | awk '{print $2}' |xargs kill
nohup java -jar deploy-test-spring.jar --spring.profiles.active=dev > nohup.out 2> nohup.err < /dev/null &

======END======
======ENV======

======END======
2021/05/07 08:55:17 Process exited with status 143 from signal TERM

`
