### ISSUE TITLE
ssh handshake

### ISSUE THREAD

**Issue by harshH-addweb** [appleboy/ssh-action#118]
Hello @appleboy ,

I am getting this error while connecting to server.

ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group-exchange-sha256]

Could you please help me.

**Comment by DeeSouza** [comment]
Did you solved? If yes, how, please?

**Comment by harnerdesigns** [comment]
@harshH-addweb I know this is a very old issue at this point, but I was curious if you came across a solution? I'm still having this issue and guessing it's the same thing you were running into back then.
