### ISSUE TITLE
possible login ssh key+password?

### ISSUE THREAD

**Issue by hermawanramadhan** [appleboy/ssh-action#121]
Hi..

I try login ssh with key + password. because I have server with required with two authentication..

but I have error: 

`can't set password and key at the same time`

how can I solve this problem?

**Comment by hermawanramadhan** [comment]
additional info: 

How can I login to that server on my PC is:
add ssh key file first using command :
`ssh-add /path/of/key.pem` 

so Can I add Identity like this here?

**Comment by appleboy** [comment]
See the documentation: https://github.com/appleboy/ssh-action#setting-up-a-ssh-key

**Comment by hermawanramadhan** [comment]
why closed? didnt solve the problem... 

login with key is success,
also with password.

but when key+password it's error like above I wrote.. some server provider need this must 2 authentication,

It's OK if not supported? just tell its sound great if suppoerted.

actually my problem already solved with "manual" ssh action remote without any 3rd party
