### ISSUE TITLE
git commands are not working in scripts section

### ISSUE THREAD

**Issue by sahibzadafahad-whizpool** [appleboy/ssh-action#125]
git commands are working in script section when use in public repository, but when I try the same commands (git commands (git pull / git status)) in script section in Private repo it does not work.

Can anybody please help me what i am doing wrong 

![action](https://user-images.githubusercontent.com/20573588/122937394-626a9880-d38b-11eb-8d72-407fe2f60cf2.JPG)

**Comment by ThomasReyskens** [comment]
same problem here

**Comment by secure12** [comment]
Apparently, you need to provide your credentials to do anything on a private repository. You could import your GitHub password or (preferably) GitHub personal access token to whichever repository runs the `git pull` command, and use that as credentials when pulling your repo. See [this issue](https://github.com/appleboy/ssh-action/issues/128)
Another way is to set up a deploy key on GitHub with your server's ssh public key.

**Comment by appleboy** [comment]
As @secure12 mention that creates a deploy key on Github is the best way for security reasons.
