### ISSUE TITLE
ForwardAgent

### ISSUE THREAD

**Issue by Laobiz** [appleboy/ssh-action#13]
Is there a way to use the ForwardAgent Option with this action? So that you could use the rsa key for example for git pull.

**Comment by appleboy** [comment]
@Laobiz Yes. I will update the documentation asap. We use the `SSH ProxyCommand`.

     +--------+       +----------+      +-----------+
     | Laptop | <-->  | Jumphost | <--> | FooServer |
     +--------+       +----------+      +-----------+
