### ISSUE TITLE
script_stop: true hinders errors

### ISSUE THREAD

**Issue by ocervell** [appleboy/ssh-action#130]
When I add `script_stop: true`, if any of the commands in the `script` section fail, I don't get any logs, just the following error:
```
======END======
2021/08/12 13:11:49 Process exited with status 1
```
I'd like the script to abort if there is an error if one of the commands, but still display the entire log, so I can know what went wrong.

Adding `debug: true` doesn't help much.

**Comment by dbistera** [comment]
Having a same issue

**Comment by appleboy** [comment]
@ocervell @dbistera Can you post your script? or see the comment first https://github.com/appleboy/ssh-action/issues/233#issuecomment-1495511649
