### ISSUE TITLE
Hows about this for a weird thing?

### ISSUE THREAD

**Issue by sunscreem** [appleboy/ssh-action#135]
If I log in via SSH from my own machine to a remote server I see PHP8.

If I log in via SSH from my friends machine to the same remote server I see PHP8.

If I log in via SSH using this package, from Github's action runner, I see PHP7.4!

Same user name, same server, same port, same key, same shell, same directory listing on log in, rebooted everything .... tried EVERYTHING lol.

Totally baffled! And I'm now posting this here in the hope that someone else has an amazing idea and says "oh.. you mean you didn't try [insert obvious thing]?"

**Comment by gokaykucuk** [comment]
Try checking if you are running the same user and login shell. I had a similar issue that I'm trying to figure out right now.

**Comment by sunscreem** [comment]
yeah - defo the same user. I thought you might have solved it with the shell.. but its bash whether from github or my own machine :(

**Comment by alexislefebvre** [comment]
Possible workaround: call the binary with `php8` or `php8.0` instead of only `php`. Or use the full path, you should see it by running `which php8.0`.

**Comment by appleboy** [comment]
Update your PATH in scripts.
