### ISSUE TITLE
Getting fatal: could not read Username for 'https://github.com': No such device or address error

### ISSUE THREAD

**Issue by devboomtech** [appleboy/ssh-action#136]
After running my yml file I can run `whoami` or even `git branch` commands but when trying git pull I get 

`fatal: could not read Username for 'https://github.com': No such device or address`

I tried the same with the `password` and `key` and get the same error

**Comment by appleboy** [comment]
@devboomtech See the solution: https://github.com/appleboy/ssh-action/issues/90#issuecomment-720046040

**Comment by kasir-barati** [comment]
> @devboomtech See the solution: [#90 (comment)](https://github.com/appleboy/ssh-action/issues/90#issuecomment-720046040)

This is not solution AFAIK @appleboy .
