### ISSUE TITLE
How do I setup proxy jump connection?

### ISSUE THREAD

**Issue by zigang93** [appleboy/ssh-action#137]
example of proxy jump ssh
`ssh -J user@serverA user@serverB`

which key I need to include?

**Comment by appleboy** [comment]
See https://github.com/appleboy/ssh-action#how-to-convert-to-yaml-format-of-githubactions

**Comment by zigang93** [comment]
@appleboy  Hi, the documentation is not clear..
serverA should put at proxy_host or just normal host?

I am getting the error
 `2021/09/*** 01:58:27 dial tcp 127.0.0.1:***: connect: connection refused`

**Comment by zigang93** [comment]
it works now..
proxy_host = my jump host
