### ISSUE TITLE
"script_stop: true" fails when script contains a  false conditional statement

### ISSUE THREAD

**Issue by VolynetsSerhii1** [appleboy/ssh-action#139]
I have a simple conditional statement in my script looking somewhat like this:

```
if [[ "${name_list}" =~ "${name}" ]]; then
                 echo "The build method is #1"
                 ...
              else
                 echo "The build method is #2"
                 ...
fi
```

Whenever the condition is false the whole job fails. I expected it to fail when an actual error happens, not when the conditional statement is false. If I get it right, it fails whenever the command's output is bigger than 0, no matter what the command is... Not quite the expected behavior.

**Comment by neongreen** [comment]
Same here:

```sh
          if git ls-remote --heads --exit-code origin "$BRANCH_OR_COMMIT" ; then
            git switch "$BRANCH_OR_COMMIT"
            git pull --ff-only
          else
            git checkout --detach "$BRANCH_OR_COMMIT"
          fi
```

**Comment by justin-pierce** [comment]
Similarly, this exits with status 1 when it should instead continue (because file does exist)

```
            if [ ! -f /path/to/file/that/exists ]
            then
            echo "File is missing, aborting!"
            exit 2
            fi
```

**Comment by dbistera** [comment]
+1

**Comment by dbistera** [comment]
======CMD======
checkInstances=""
  
  
check=0
if [ -n "$checkInstances" ]
  then
    echo "Killing runned containers"
    echo $"[ -z "$checkInstances" ]"
    echo "$ab"
    check=1
  
  fi
  echo "$check"

======END======
2023/02/09 14:08:33 Process exited with status 1
Im pretty sure that it fails when we using only if

**Comment by appleboy** [comment]
> If I get it right, it fails whenever the command's output is bigger than 0, no matter what the command is... Not quite the expected behavior.

You are right.

**Comment by go-utsav** [comment]
Hit this today with `script_stop: true` + an `if/else` where the condition was false (empty env var). Job died with no stderr, just `Process exited with status 1`.

`if` without `else` is fine. `else` is what blows up.

Workaround — skip `if/else`, use `&&` / `||`:

```sh
# bad: false condition + else => status 1
if [ -n "${APP_VERSION_API_TOKEN}" ]; then
  printf '%s=%s\n' "APP_VERSION_API_TOKEN" "${APP_VERSION_API_TOKEN}" >> "$TMP_ENV"
else
  grep -E '^APP_VERSION_API_TOKEN=' "$ENV_FILE" >> "$TMP_ENV" || true
fi

# good
[ -n "${APP_VERSION_API_TOKEN}" ] && printf '%s=%s\n' "APP_VERSION_API_TOKEN" "${APP_VERSION_API_TOKEN}" >> "$TMP_ENV" || grep -E '^APP_VERSION_API_TOKEN=' "$ENV_FILE" >> "$TMP_ENV" || true
