### ISSUE TITLE
Getting tar error, no clue what it means..

### ISSUE THREAD

**Issue by amen-ma** [appleboy/ssh-action#145]
![image](https://user-images.githubusercontent.com/66905824/146784154-9fabb025-1197-4d0c-b543-88feb5588331.png)
 - uses: actions/checkout@v2

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "Puffy-Bot/*"
          target: "/var/Discord/Puffy-Bot"
          strip_components: 1

This is the action that is tripping up the workflow. Not sure what I am doing wrong...
Error is as follows (in case image does not load):

**tar all files into /tmp/295860149/dwnchxqSnj.tar
tar: empty archive
exit status 1**

**Comment by socraticDevBlog** [comment]
are u sure your user has the permission to write to `/var/Discord/Puffy-Bot` ?
quick test: change file transfer target to a directory in your user space : for example `~/myDirectory`
or
on your VPS try to move files from your user space to `/var/Discord/Puffy-Bot`

**Comment by amen-ma** [comment]
No worries! I realized my hostname was incorrect. I also was using my VPS with just root user, not creating a user with sudo privileges lol. Thank you for responding and trying to help nonetheless!
