### ISSUE TITLE
Ubuntu 22.04 compatibility issue?

### ISSUE THREAD

**Issue by mikkokotila** [appleboy/ssh-action#157]
With Ubuntu 22.04 get 

```
======END======
2022/04/30 14:09:58 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

With Ubuntu 20.04 everything works just fine. Nothing else changed, just the Ubuntu version change and the result is that `ssh-action` stops working.

**Comment by Syzuna** [comment]
yes this seems to be related to openssh 8.8p1-1 and up not accepting ssh-rsa key types by default.
for now you can add "PubkeyAcceptedKeyTypes=+ssh-rsa" to your /etc/ssh/sshc_config.
dont forget to restart the sshd service afterwards with "sudo systemctl restart sshd"
