### ISSUE TITLE
Cleanup is not defined in action.yml

### ISSUE THREAD

**Issue by horia-stoenescu** [appleboy/ssh-action#160]
In case a self hosted runner is used with this `ssh-action`, the built images are not removed at the end (`post-entrypoint` is missing from `action.yml`) - example:
```
docker image ls  | grep 3666c5
3666c5                                                                              6d7df4da89a843fa8236a7b86921eb38   ca3dce6a6532   About an hour ago   13.6MB

docker image ls  | grep appleboy/drone-ssh
appleboy/drone-ssh                                                                  1.6.3-linux-amd64                  47f94d42e479   18 months ago       13.6MB
```

The only solution for not is to add a new step in job that deletes them.
A cleanup script should be implemented and called from `action.yml`.

Also, in case a job that is using `ssh-action` hangs and then the workflow is cancelled, the container will be still up on the self hosted runner.

**Comment by appleboy** [comment]
try the https://github.com/appleboy/ssh-action/releases/tag/v1.2.0 version without Docker environment.
