### ISSUE TITLE
Running a script which fetches from github doesn't work

### ISSUE THREAD

**Issue by alalfakawma** [appleboy/ssh-action#165]
```
======CMD======
cd /var/www/my-site
./deploy_script.sh
======END======
out: Deploying application...
out: 
out:                                           
out:   The "--message" option does not exist.  
out:                                           
out: 
err: git@github.com: Permission denied (publickey).
err: fatal: Could not read from remote repository.
err: 
err: Please make sure you have the correct access rights
err: and the repository exists.
2022/06/29 13:08:46 Process exited with status 128
```

I get this error when trying to use `git fetch` inside a script, does this mean the keys are not being forwarded by the action? Is there a way I can forward the keys to the server? Like `ssh -A user@something.com`? Would really be happy to know as I'm not finding anything in the docs.

**Comment by EduardoJM** [comment]
Here (using git pull), the solution that worked for me to made an correct pull of the repository updates is that: https://github.com/appleboy/ssh-action/issues/90#issuecomment-1173148488

Is not an really good yml and code, but worked

**Comment by alalfakawma** [comment]
Wish there was an option to forward the current ssh key to the connected server, this would make it much easier to just get in the server and get out without leaving any information on the server. Right now i'm also using what you're using, a personal access token to pull from the repo, this is annoying as you've to put your personal token on a repo that is not yours.

**Comment by appleboy** [comment]
See the solution: https://github.com/appleboy/ssh-action/issues/232#issuecomment-1506493783

**Comment by khurshid-alam** [comment]
@appleboy How to use different ssh-key for server login and depoyment?

 Github doesn't let you use same key you added in profile and deployment. It would say "key is in use"
