### ISSUE TITLE
Command not exist

### ISSUE THREAD

**Issue by mikedowndown** [appleboy/ssh-action#173]
In installed go in my remote host and the command is valid. However, when I use go command in the ssh-action script, I encountered the following error:

```
out: go vet ./...
err: make: go: Command not found
err: make: *** [check] Error 127
2022/07/24 05:26:33 Process exited with status 2
```

**Comment by AlexWestergaard** [comment]
Does the SSH-User have access to that command?

Try pathing the go executable `/usr/local/go/bin` as in `/usr/local/go/bin vet ./...`

**Comment by mikedowndown** [comment]
OK, I'll try.

**Comment by appleboy** [comment]
If you have any further questions, please reopen this Issue.
