### ISSUE TITLE
Action version v0.1.5 causing multiple `err:` outputs

### ISSUE THREAD

**Issue by rxa313** [appleboy/ssh-action#174]
After the recent release of `v0.1.5`, I checked my logs and notice the output after script is returning loads of unnecessary `err:` outs.

`v0.1.5`: 
```
======CMD======
pwd

======END======
out: /home/***
err: 
err: 
err: 
err: 
out: 
out: 
err: 
err: 
err: 
out: 
err: 
out: 
err: 
err: 
out: 
err: 
out: 
err: 
err: 
err: 
err: 
err: 
out: 
err: 
out: 
err: 
err: 
out: 
err: 
out: 
err: 
out: 
err: 
err: 
err: 
out: 
err: 
err: 
err: 
out: 
out: 
out: 
err: 
err: 
out: 
out: 
out: 
err: 
out: 
err: 
out: 
err: 
err: 
out: 
out: 
out: 
out: 
err: 
err: 
err: 
err: 
err: 
out: 
out: 
out: 
err: 
out: 
err: 
err: 
err: 
err: 
err: 
err: 
err: 
err: 
err: 
==============================================
✅ Successfully executed commands to all host.
==============================================
```

I tested using `v0.1.4` and it returns the correct output:
```
======CMD======
pwd

======END======
out: /home/***
==============================================
✅ Successfully executed commands to all host.
==============================================
```

**Comment by linucks** [comment]
Same here.

**Comment by gamoreli** [comment]
Same here.

**Comment by jeromecoupe** [comment]
Same issue here, with multiple commands (PHP and Node scripts). If I compare the output to `v0.1.4`:
- Everything executes and works as planned, including outputs.
- I get a long list (70 lines or so) of `err` and `out` statements
- After the list, I get the `✅ Successfully executed commands to all host.` line

**Comment by yyjlincoln** [comment]
Seems like it was introduced by `drone-ssh`:
https://github.com/appleboy/drone-ssh/issues/192

**Comment by fredcohen-aa** [comment]
Same thing. Sometimes it's hundreds of blank err: and out: lines for no apparent reason

**Comment by indymaat** [comment]
Same issue here, using appleboy/ssh-action@v0.1.5

Everything works as expected but just a veeeeryy long output...

```
4746 out: 
4747 out: 
4748 err: 
4749 out: 
4750 err: 
4751 out: 
4752 ==============================================
4753 ✅ Successfully executed commands to all host.
4754 ==============================================
```

**Comment by kanes115** [comment]
Same here

**Comment by Stas-AbsoluteDesign** [comment]
@appleboy apart from using a specific old version as per https://github.com/appleboy/ssh-action/issues/174#issuecomment-1214552175 suggestion above.. is there any proper fix planned? :(

**Comment by PekayTab** [comment]
Experiencing the same problem on the laravel project
![image](https://user-images.githubusercontent.com/36557751/200149641-e18511f4-b592-4922-8334-64cc2f6744e7.png)
![image](https://user-images.githubusercontent.com/36557751/200149655-a959c231-6811-40e7-9adb-46db6e805c71.png)

**Comment by brianjmurrell** [comment]
> dce9d565de8d876c11d93fa4fe677c0285a66d78

When I switch from `master` to this commit I get authentication errors:

```
2022/11/16 19:30:56 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Please try the v0.1.6 version. https://github.com/appleboy/ssh-action/releases/tag/v0.1.6

**Comment by webbyus** [comment]
> Please try the v0.1.6 version. https://github.com/appleboy/ssh-action/releases/tag/v0.1.6

<img width="982" alt="image" src="https://github.com/appleboy/ssh-action/assets/43690533/e64f67f9-aadc-4efb-ab8a-ecc3cd50c2c6">
