### ISSUE TITLE
Extract file to wrong folder

### ISSUE THREAD

**Issue by Elikill58** [appleboy/ssh-action#182]
I can't extract files to folder, it always create sub folder.
My YML:
```
source: "my/dir/*"
target: "/folder"
```
But all files are at `folder/my/dir` instead of just `folder`.

How can I fix it ?

**Comment by appleboy** [comment]
Please set `strip_components: 2` and this is scp-action issue not ssh-action.

**Comment by appleboy** [comment]
See https://github.com/appleboy/scp-action/issues/50
