### ISSUE TITLE
Got many empty line before end the step

### ISSUE THREAD

**Issue by hootpy** [appleboy/ssh-action#187]
Just before our step is done, the output is filled with so many empty lines like this, even though I used simple commands like `ls -a`.

Do I need to config anything else?

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/45201848/194031552-4b4f7d43-a3bb-43b2-b179-febcd821c44b.png">

**Comment by kanes115** [comment]
I'm getting the same. Would love to see this resolved!

**Comment by nkl90** [comment]
Yes, and I
![Снимок экрана_2022-10-13_12-42-51](https://user-images.githubusercontent.com/3640423/195521555-f8812257-184f-45c7-b833-cd198e341c37.png)
![Снимок экрана_2022-10-13_12-44-24](https://user-images.githubusercontent.com/3640423/195521679-ac13bdca-b372-4bdc-825d-7cf15f891679.png)

**Comment by IonPalii** [comment]
Same for me, around ±1900 lines

**Comment by l4lilul3lo** [comment]
same, 4000 lines

**Comment by cedsana** [comment]
Same, few hundreds lines for each command.

**Comment by jeromecoupe** [comment]
Reported / discussed in https://github.com/appleboy/ssh-action/issues/174 and https://github.com/appleboy/ssh-action/issues/179

**Comment by kolosovpetro** [comment]
Same

https://github.com/kolosovpetro/kolosovpetro.github.io/actions/runs/3357942785/jobs/5564241222

**Comment by marefati110** [comment]
any update?

**Comment by Luttik** [comment]
Same

**Comment by appleboy** [comment]
Please try the v0.1.6 version https://github.com/appleboy/ssh-action/releases/tag/v0.1.6

**Comment by Luttik** [comment]
Great that fixes it 👍
