### ISSUE TITLE
Error: missing server host

### ISSUE THREAD

**Issue by Maxim-Chugaev** [appleboy/ssh-action#19]
`with:
    host: ***
    username: ***
    script: whoami
    debug: true`

i have error, why?

**Comment by Dzheky** [comment]
I had the same issue, check the version of ssh-action you are using in your yaml

**Comment by appleboy** [comment]
See: https://github.com/appleboy/ssh-action/blob/73767290ca0fd123c19a35598c66b657bd72999b/.github/workflows/ci.yml#L11-L16

Please provide the version of ssh-action

**Comment by DanielFerguson** [comment]
I'm having this same issue with v0.0.2

**Comment by Lotuashvili** [comment]
Same error here. Any fixes?

**Comment by thomersch** [comment]
Somehow Github is pushing an old version to the top of the search results. Update to 0.0.7 and everything is gonna be good :)

**Comment by appleboy** [comment]
Yes. Please make sure your plugin version.

**Comment by SCM-JAMCRACKER** [comment]
Error: missing server host ---- Getting this error only for some instances. Can you please provide any suggestions?

**Comment by appleboy** [comment]
@SCM-JAMCRACKER What is your ssh-action version? Please help to open a new issue.

**Comment by UsamaMalick** [comment]
@appleboy 
Getting same error for instances where it was working fine few weeks ago.
tried these versions: appleboy/ssh-action@v0.1.10 and appleboy/ssh-action@master

**Comment by lukynmatuska** [comment]
Hi, I'm having this problem after upgrade to v1.0.0
For more information see https://github.com/lukynmatuska/vvcb-firesporteu-middleware/actions/runs/5851266797/job/15865387674

**Comment by lukynmatuska** [comment]
I removed the `env` section and now it works fine.
How is mentioned in https://github.com/appleboy/ssh-action/issues/239.

**Comment by shtse8** [comment]
I am using `with`, but the same error happens.

**Comment by adityapanther-vaionex** [comment]
I am having same issue

**Comment by appleboy** [comment]
@shtse8 Share your config?

**Comment by shurale85** [comment]
Have the same issue. We have two repos, it is fine for one of them and failed for another

**Comment by kokila-elastic** [comment]
i am having server host  error

**Comment by PiotrBracha** [comment]
I use:
`        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ANSIBLE_MANAGEMENT_IP }}
          username: ${{ secrets.ANSIBLE_MANAGEMENT_USER }}
          key: ${{ secrets.ANSIBLE_MANAGEMENT_SSH_KEY }}
          script: |`

debug logs shows:
`
##[debug]Evaluating: secrets.ANSIBLE_MANAGEMENT_SSH_KEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ANSIBLE_MANAGEMENT_SSH_KEY'
##[debug]=> null
##[debug]Result: null

[...]
2025/02/05 13:10:37 Error: missing server host
##[debug]Docker Action run completed with exit code 1
`

Somehow secret with ssh key is evaluated as "null". In another repository I also use the same part:
`
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ANSIBLE_MANAGEMENT_IP }}
          username: ${{ secrets.ANSIBLE_MANAGEMENT_USER }}
          key: ${{ secrets.ANSIBLE_MANAGEMENT_SSH_KEY }}
          script: |
`
and there is no problem.
