### ISSUE TITLE
Facing issue : If i used private ip for secrets.HOST getting this error "20***/11/25 07:26:30 dial tcp ***:***: i/o timeout"  &  If i used Public IP for secrets.HOST getting this error "20***/11/25 07:08:43 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain""

### ISSUE THREAD

**Issue by rajuvgit** [appleboy/ssh-action#193]
My yaml file

name: SSH to DO 

on:
  workflow_dispatch:
    inputs:
        
      demo-server:
        type: boolean
        description: 'MultiBuild -SSH key'
        default: "false"
        required: true
        
jobs:
  deploy-DO:
    name: Job ID - ${{ github.run_number }} || Pipeline User - ${{ github.actor }}
    runs-on: ubuntu-latest
    if: |
        contains(github.event.inputs.demo-server, 'true')
    steps:
    - name: Deploy to DO server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}      
      
        script: |
          pwd

**Comment by appleboy** [comment]
duplicated of https://github.com/appleboy/ssh-action/issues/80
