### ISSUE TITLE
20***/12/01 11:13:55 dial tcp ***:***: i/o timeout

### ISSUE THREAD

**Issue by pradeep-sparkout** [appleboy/ssh-action#194]
I don't understand thats error. Its meaning can not connect to my server?

======CMD======
cd /var/www/html/project/

git pull origin main

sudo chmod -R 777 deploy.sh

./deploy.sh

======END======

20***/12/01 10:40:37 dial tcp :: i/o timeout

My workflow file also given below:

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          key: ${{ secrets.SSH_PRIVATEKEY_DEV }}
```How to fix this Error????
@appleboy 
I deployed laravel project in ubuntu server using Github-Action.But this 
**10:40:37 dial tcp ***:***: i/o timeout** error displayed...
How to Fix this error ???Anybody response to me... How to fix Error???**

**Comment by mabar** [comment]
Yeah, it is an connection error. Your server could be either unreachable or timeouts due to wrong configuration on server (it happens to me only sometimes on some servers)

It is probably not an error in this library

**Comment by pradeep-sparkout** [comment]
> Yeah, it is an connection error. Your server could be either unreachable or timeouts due to wrong configuration on server (it happens to me only sometimes on some servers)
> 
> It is probably not an error in this libOkiee 


Thank you....I found and solved that error.That is vpn issue...I solved it...

**Comment by pradeep-sparkout** [comment]
Solved it

**Comment by mihir8400** [comment]
@pradeep-sparkout , can you please explain how to resolve ?
![image](https://github.com/user-attachments/assets/87ac9a84-3228-4e7b-801b-0c82f89b3262)

`name: Deploy Laravel Application

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SFTP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.SFTP_PRIVATE_KEY }}
        port: 22
        script: |
          rsync -avz --exclude 'vendor' --exclude 'node_modules' . ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PATH }}`
