### ISSUE TITLE
What is the meaning of this ? Fix it asap i need to upload files to server

### ISSUE THREAD

**Issue by vipulwalia** [appleboy/ssh-action#195]
![Capture](https://user-images.githubusercontent.com/81367183/206105233-4b6702cc-5d0d-4c66-902e-e18fdabbd0da.PNG)

**Comment by JalajGoswami** [comment]
![image](https://user-images.githubusercontent.com/78695061/206106364-3f006029-e52d-4390-a49d-eb3a10e480ff.png)
Facing the same issue, with all my workflows

**Comment by amanasterdio** [comment]
Yes, I am facing the same issue with my workflows

**Comment by vipulwalia** [comment]
> Use previous version appleboy/ssh-action@v0.1.5

Where do you want me to specify the version ? 
![yml_file](https://user-images.githubusercontent.com/81367183/206109478-c70f28dd-1bfd-4173-807f-e946f4223550.PNG)

Instead of 
`appleboy/ssh-action@master`
to 
`appleboy/ssh-action@v0.1.5` 

Like this ?

**Comment by cliffordwhansen** [comment]
> > Use previous version appleboy/ssh-action@v0.1.5
> 
> Where do you want me to specify the version ? ![yml_file](https://user-images.githubusercontent.com/81367183/206109478-c70f28dd-1bfd-4173-807f-e946f4223550.PNG)
> 
> Instead of `appleboy/ssh-action@master` to `appleboy/ssh-action@v0.1.5`
> 
> Like this ?

That is correct :-)

**Comment by vipulwalia** [comment]
Yes resolved and working fine, thx alot for help.
