### ISSUE TITLE
is it update problem?

### ISSUE THREAD

**Issue by troysw** [appleboy/ssh-action#196]
![화면 캡처 2022-12-07 153119](https://user-images.githubusercontent.com/45636035/206106022-08869493-57aa-4511-baac-c7c2aaf45f12.jpg)

It worked fine before your update, but maybe something went wrong during the update?

**Comment by Nomango** [comment]
+1. I am going back to version v0.1.5

**Comment by aineland** [comment]
Same error here as well.

**Comment by lina1919** [comment]
Same error here :(

**Comment by sudipto-28** [comment]
Same error.

**Comment by ferasalhallaknamaa** [comment]
Same error.

**Comment by vamshiOmniWorks** [comment]
Same here.

**Comment by prakash559** [comment]
same error here....Its just started few minutes ago.

**Comment by nggepe** [comment]
same here

**Comment by amanasterdio** [comment]
Try using the previous version as stated by @apervikov. Its working fine

**Comment by vipulwalia** [comment]
Here https://github.com/appleboy/ssh-action/issues/195#issuecomment-1340481608

**Comment by riyandharne-123** [comment]
same here
