### ISSUE TITLE
“ appleboy/drone-ssh:1.6.5-linux-amd64 not found”  Solutions

### ISSUE THREAD

**Issue by oneoy** [appleboy/ssh-action#197]
github actions build.yaml ` uses: appleboy/ssh-action@master`
Error response from daemon: manifest for appleboy/drone-ssh:1.6.5-linux-amd64 not found: manifest unknown: manifest unknown

you should docker push `appleboy/drone-ssh:1.6.5-linux-amd64` to hub.docker.com

use ` uses: appleboy/ssh-action@v0.1.4`  is Work

**Comment by adam-skalicky** [comment]
Looks like there was a release in a downstream dependency - https://github.com/appleboy/drone-ssh

I see v1.6.5 was released an hour ago which is around when my builds started failing too. Raised https://github.com/appleboy/drone-ssh/issues/204 over there.

**Comment by draconid719** [comment]
![image](https://user-images.githubusercontent.com/60066694/206114061-049b6d03-3d3e-4ab3-8585-836a811873a4.png)
Me, too, it was working yesterday.

**Comment by oneoy** [comment]
@draconid719  `uses: appleboy/ssh-action@v0.1.4` is Work
![image](https://user-images.githubusercontent.com/38435398/206114138-f0d95e34-cc84-463f-9f6f-95e11c82b1cd.png)

**Comment by sinashaloudegi** [comment]
I have the same problem, my builds started to fail for the last hour, which I assume it is due to the changes in this commit 687fe57bd73a8981875573abc46ab275b456e0dc

**Comment by oneoy** [comment]
> I have the same problem, my builds started to fail for the last hour, which I assume it is due to the changes in this commit [687fe57](https://github.com/appleboy/ssh-action/commit/687fe57bd73a8981875573abc46ab275b456e0dc)

Anyone who understands the principle of actions should know that it uses docker images to complete part of the work, so you need to specify the next version  ` uses: appleboy/ssh-action@v0.1.4`  is Work

**Comment by adam-skalicky** [comment]
> 

v0.1.4 works, but master is broken. Using @master will result in the error described. As @sinashaloudegi mentioned https://github.com/appleboy/ssh-action/commit/687fe57bd73a8981875573abc46ab275b456e0dc has created a dependency on a version that is not accessible on build. It should be rolled back until this the image appleboy/drone-ssh:1.6.5-linux-amd64 is posted on dockerhub.

The documentation for this plugin all points to master, so I suspect that there are a lot of broken builds right now.

**Comment by hunghg2505** [comment]
thanks you

**Comment by meotimdihia** [comment]
I am getting the error when reverting to v0.1.4: 2022/12/07 09:06:27 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by SrihariharaanS** [comment]
uses: appleboy/ssh-action@master is working now

**Comment by oneoy** [comment]
[1.6.5-linux-amd64](https://hub.docker.com/layers/appleboy/drone-ssh/1.6.5-linux-amd64/images/sha256-533b08cbdf0d6ac25edea856bff2d3c385b505aee64d6c475f7952d8c17da9e4?context=explore) 
Published Question resolved I suggest not to use: `appleboy/ssh-action@master`
It is recommended to use: `appleboy/ssh-action@v0.1.5`
