### ISSUE TITLE
envs must be uppercase?

### ISSUE THREAD

**Issue by fernandocristan** [appleboy/ssh-action#204]
Variables in 'env' being lowercase are not transferred to scripts.

I made copy this [example](https://github.com/appleboy/ssh-action#pass-environment-variable-to-shell-script) adding a variable 'Test' with value 'Test', added it to 'envs' and a script 'echo "This is a $Test"' and it didn't work.

output:

======CMD======
echo "I am $FOO"
echo "I am $BAR"
echo "sha: $SHA"
echo "This is a $Test"

======END======
out: I am BAR
out: I am FOO
out: sha: bc413be962ef75cb38...
out: This is a

---

Is that right?

**Comment by appleboy** [comment]
Yes. ENVs must be uppercase.
