### ISSUE TITLE
getting no such hosts when giving ip address or dns name of EC2

### ISSUE THREAD

**Issue by changan1111** [appleboy/ssh-action#205]
getting no such hosts when giving ip address or dns name of EC2 but the instance are up and running

**Comment by changan1111** [comment]
https://stackoverflow.com/questions/74871489/no-such-host-when-connecting-ec2-through-ssh-using-githubactions-terraform

**Comment by appleboy** [comment]
Please post your EC2 information such as `Public IPv4 DNS` or bind `Elastic IP addresses` with your ec2 instance.
