### ISSUE TITLE
npm command not found

### ISSUE THREAD

**Issue by yy921010** [appleboy/ssh-action#21]
I have npm installed on my server, why does the 'npm command not found' error during deployment?

**Comment by rieckpil** [comment]
I encountered a similar problem where Maven (Java Build Tool) was not available within my SSH session but installed on the server:

```
 ======CMD======
cd /***/projects/xyz
git pull
mvn clean package

======END======
err: From https://github.com/xyz
err:    a6e1f0a..0efd9b7  master     -> origin/master
out: Updating a6e1f0a..0efd9b7
out: Fast-forward
out:  .github/workflows/maven.yml | 5 +++--
out:  1 file changed, 3 insertions(+), 2 deletions(-)
err: bash: line 2: mvn: command not found
2020/01/08 18:15:58 Process exited with status 127
##[error]Docker run failed with exit code 1
```

**Comment by SimonSun1988** [comment]
i have this error too.

**Comment by SimonSun1988** [comment]
@yy921010 try this, fixed my problem

```yml
script: |
  export NVM_DIR=~/.nvm
  source ~/.nvm/nvm.sh
  npm --help

```

**Comment by yy921010** [comment]
> @yy921010 try this, fixed my problem
> 
> ```yaml
> script: |
>   export NVM_DIR=~/.nvm
>   source ~/.nvm/nvm.sh
>   npm --help
> ```

thanks!!

**Comment by apardo04** [comment]
> @yy921010 try this, fixed my problem
> 
> ```yaml
> script: |
>   export NVM_DIR=~/.nvm
>   source ~/.nvm/nvm.sh
>   npm --help
> ```

Do you know why this fixed the problem?

**Comment by SimonSun1988** [comment]
i think because docker not export environment

**Comment by nathanhannig** [comment]
Why is it not loading the users .bashrc correctly?

**Comment by fcbuz2000** [comment]
npm: command not found
Reason:
I use nvm for the server node environment, and nvm will not install the node environment in the /usr/local/bin/ directory, so that sudo can't find the corresponding instructions, and finally create a soft connection to solve

sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/pm2" "/usr/local/bin/pm2"

you can test "sudo npm -v"

https://blog.csdn.net/weixin_40599109/article/details/110825357

**Comment by vanyauhalin** [comment]
> Why is it not loading the users .bashrc correctly?

@nathanhannig, maybe `exec bash` can help you (this solved my problem):

```sh
script: |
  exec bash
  pm2 reload app.js
```

**Comment by oshanz** [comment]
thanks for the information @vanyauhalin 
to solve my issue I needed to do a minor change to your code. apparently, you need to get a login shell. so you can load all bash variables and configurations.
```yml
        script: |
          exec bash \-l
          cd ~/project-dir
          ./deploy.sh
```

it seems what "appleboy/ssh-action" underline do is a sh shell, not a bash shell. it's similar to
```bash
ssh a@b -t sh
```

**Comment by hyoretsu** [comment]
None of the above worked for me. `exec bash` worked but didn't run my command.

**Comment by stepanjakl** [comment]
Hello all, I have been facing the same issue. @oshanz pointed out well that when logging through the SSH, the shell is in an interactive mode instead of a login mode. So, some profile information and paths are not loaded. More on this issue [here](https://unix.stackexchange.com/a/46856/558963).

In any case, I managed to get it working with a here document syntax:

```yaml
script: |
    bash -l -c "$(cat <<- EOF
    echo "This should work"
    EOF
    )"
```

There's just one issue, I keep getting this error `err: bash: line 107: [: -ne: unary operator expected` on some lines. Fortunately, it doesn't stop the script even with `script_stop: true`.

I think this might also be a (bit hacky) solution for #31.

**Comment by fperaltalitebox** [comment]
> > @yy921010 try this, fixed my problem
> > ```yaml
> > script: |
> >   export NVM_DIR=~/.nvm
> >   source ~/.nvm/nvm.sh
> >   npm --help
> > ```
> 
> Fixed it for me as well! Thank you. Do you know why this fixed the problem?

This works for me too.

**Comment by dhrubkumar50** [comment]
> thanks for the information @vanyauhalin to solve my issue I needed to do a minor change to your code. apparently, you need to get a login shell. so you can load all bash variables and configurations.
> 
> ```yaml
>         script: |
>           exec bash \-l
>           cd ~/project-dir
>           ./deploy.sh
> ```
> 
> it seems what "appleboy/ssh-action" underline do is a sh shell, not a bash shell. it's similar to
> 
> ```shell
> ssh a@b -t sh
> ```
 Adding this Help me Thanks you..😍😍😍

**Comment by goldthree-shit** [comment]
> I encountered a similar problem where Maven (Java Build Tool) was not available within my SSH session but installed on the server:
> 
> ```
>  ======CMD======
> cd /***/projects/xyz
> git pull
> mvn clean package
> 
> ======END======
> err: From https://github.com/xyz
> err:    a6e1f0a..0efd9b7  master     -> origin/master
> out: Updating a6e1f0a..0efd9b7
> out: Fast-forward
> out:  .github/workflows/maven.yml | 5 +++--
> out:  1 file changed, 3 insertions(+), 2 deletions(-)
> err: bash: line 2: mvn: command not found
> 2020/01/08 18:15:58 Process exited with status 127
> ##[error]Docker run failed with exit code 1
> ```

Hey，Gay , I encountered too. So how do you work out? Thank you

**Comment by sabuhiteymurov** [comment]
> > I encountered a similar problem where Maven (Java Build Tool) was not available within my SSH session but installed on the server:
> > ```
> >  ======CMD======
> > cd /***/projects/xyz
> > git pull
> > mvn clean package
> > 
> > ======END======
> > err: From https://github.com/xyz
> > err:    a6e1f0a..0efd9b7  master     -> origin/master
> > out: Updating a6e1f0a..0efd9b7
> > out: Fast-forward
> > out:  .github/workflows/maven.yml | 5 +++--
> > out:  1 file changed, 3 insertions(+), 2 deletions(-)
> > err: bash: line 2: mvn: command not found
> > 2020/01/08 18:15:58 Process exited with status 127
> > ##[error]Docker run failed with exit code 1
> > ```
> 
> Hey，Gay , I encountered too. So how do you work out? Thank you

```
export PATH="/home/{username}/.nvm/versions/node/v{version}/bin:$PATH"
```

This worked out for me, just replace {username} with your actual username, and {version} with your node version (for me it was 20.9.0)

**Comment by sabuhiteymurov** [comment]
> > I encountered a similar problem where Maven (Java Build Tool) was not available within my SSH session but installed on the server:
> > ```
> >  ======CMD======
> > cd /***/projects/xyz
> > git pull
> > mvn clean package
> > 
> > ======END======
> > err: From https://github.com/xyz
> > err:    a6e1f0a..0efd9b7  master     -> origin/master
> > out: Updating a6e1f0a..0efd9b7
> > out: Fast-forward
> > out:  .github/workflows/maven.yml | 5 +++--
> > out:  1 file changed, 3 insertions(+), 2 deletions(-)
> > err: bash: line 2: mvn: command not found
> > 2020/01/08 18:15:58 Process exited with status 127
> > ##[error]Docker run failed with exit code 1
> > ```
> 
> Hey，Gay , I encountered too. So how do you work out? Thank you

You have to export mvn path, try to use ```echo $PATH``` with ssh-action and on your actual server, compare the results.

**Comment by goldthree-shit** [comment]
Thank you, it is useful;

**Comment by ilnytskyi** [comment]
I faced similar issues with github actions and building node packages. But nothing helped.

I found a workaround: to spawn a docker with same node version, mount on same paths and user. (add your envs if needed)
And build the app inside docker, then execute all other commands e.g. supervisor that work ok with appleboy/ssh-action
Maybe not perfect solution, but solves all strange problems related to exporting paths or broken envs in child processes or bash vs sh

```
... some commands that work

docker run --rm -v $(pwd):$(pwd) \
  -w $(pwd) \
  -u $(id -u):$(id -g) \
  node:$(cat .nvmrc | sed 's/^v//') \
  bash -c "yarn && yarn build"

... some other commands
```

**Comment by dr5hn** [comment]
When using exec bash \-l in GitHub Actions SSH deployments on Ubuntu 24.04, you may encounter issues with shell initialization. The fix involves modifying the ~/.bashrc file.

Find and comment out these lines in your ~/.bashrc:

```bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return
```

This modification allows non-interactive shell sessions (like those used in GitHub Actions) to properly load environment variables and shell configurations. The default behavior prevents environment loading in non-interactive shells, which can cause problems with deployment scripts.

Credits: https://serverfault.com/questions/936746/bashrc-is-not-sourced-on-ssh-command/1172128#1172128
