### ISSUE TITLE
Commands that fail do not cause actions to fail

### ISSUE THREAD

**Issue by Wykaz** [appleboy/ssh-action#211]
My action worked successfully while the commands executed over ssh did not work. I think it shouldn't work like this.

In the following example, the command has an error but the GitHub action is marked as successful with success.
```
======CMD======
cd ***
git pull
pnpm install
tmux send-keys -t update-session 'pnpm start' Enter

======END======
err: bash: line 1: cd: /home/***/project/games-utils/fetch-data/hypxiel/skyblock: No such file or directory
err: fatal: not a git repository (or any of the parent directories): .git
out:  ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /home/***
==============================================
✅ Successfully executed commands to all host.
==============================================
```

**Comment by huedaya** [comment]
It just happened a few hours ago, it's possible because of yesterday's update?

![image](https://user-images.githubusercontent.com/4969689/211258912-e65daf1e-2bc0-4548-9763-03cb3d0aa090.png)

**Comment by Wykaz** [comment]
For info I looked at the doc again? I didn't see the option : "script_stop: true" to change this functionning
