### ISSUE TITLE
Automatic port being added to the host from .env file

### ISSUE THREAD

**Issue by Ryuk-hash** [appleboy/ssh-action#213]
**Using**: ssh-action@master
**In-app port**: 3000 inside the .env file with the name "PORT"
**Problem**: connection timeout error; action's using .env defined application port instead.
**Fix**: Renamed "PORT" in your app to "APP_PORT" and it worked.

Please look at why it's using the variables from inside the .env file and not its default provided ones.

**Script**:
```
- name: restart
        uses: appleboy/ssh-action@master
        with:
          key: ***
          host: ***
          username: 'ubuntu'
          script: |
            nvm use 14.18.3
            cd ...
            sudo npm i
            pm2 restart ...
```

**After execution**: (restart script fails)
```
======CMD======

nvm use 14.18.3
cd ...
sudo npm i
pm2 restart ...

======END======
2023/01/10 08:39:13 dial tcp {HOST}:3000: i/o timeout
```

**Comment by tklivan** [comment]
same issue. since 0.1.7 its reading from my .env file the variable PORT

**Comment by appleboy** [comment]
I will remove the unused global variable like `PORT` conflicts with the custom variable from .env file.
