### ISSUE TITLE
Release 0.1.7 [Bug] -- "ssh: handshake failed: EOF" error

### ISSUE THREAD

**Issue by StaysenseWesMelton** [appleboy/ssh-action#216]
Since updating to 0.1.7, our deploy config has started failing with the step that uses this action with the following error: 

`ssh: handshake failed: EOF`

We downgraded to `0.1.6` and the issue resolves. 

Example code snippet from our deployment action that fails with `0.1.7`:

```yaml
 script: |
    cd /home/deploy/myapp/
    tar -xzf "$(date '+%Y-%m-%d')-myapp.tar.gz" -C .
    cd dist
    cp -ua . /var/www/myapp
    cd /var/www/myapp/
    ls -hal
    npm install --production
    pm2 reload ecosystem.config.json --env production
```

**Comment by appleboy** [comment]
Please try the latest version.
