### ISSUE TITLE
dial tcp 3.***.**5.***:***: connect: connection refused

### ISSUE THREAD

**Issue by aamiralihussain** [appleboy/ssh-action#224]
I tried to ssh into EC2 instance.

1. I have configured required Inbound Rules in EC2 instance: all tcp, ssh, traffic rules.
2. I have added RSA PRIVATE KEY to github secrets from .pem file that is used to be authorized via ssh : command used-> cat file.pem

However, it always failed to established connection. 
Got this error: **dial tcp 3.***.**5.***:***: connect: connection refused**
Below is the workflow:

` deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
    - name: Pull docker image from ecr and deploy to ec2 and Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.7
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        PORT: ${{ secrets.PORT }}
        IMAGE_TAG: 1.3.15
      with:
        host: ${{ secrets.EC2_HOST_DNS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: ECR_REGISTRY,ECR_REPOSITORY,PORT,IMAGE_TAG
        script: |
            cd /home/ubuntu/prod
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker run -p $PORT:8009 -d $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG`

**Comment by shanulhabib** [comment]
I just resolve the issue my RSA PRIVATE KEY was incomplete
Try to run cat ~/.ssh/id_rsa
Thx.

**Comment by aamiralihussain** [comment]
> I just resolve the issue my RSA PRIVATE KEY was incomplete Try to run cat ~/.ssh/id_rsa Thx.

I already copied private key from pem file, which I used to login to ec2 via ssh and it is already placed in authorisedKey. Is this still to do?

**Comment by appleboy** [comment]
@aamiralihussain Please show your output Log.

**Comment by appleboy** [comment]
Try the latest version.
