### ISSUE TITLE
Security tool identified an issue: The Docker container is configured to run as the root user.

### ISSUE THREAD

**Issue by tpatil30** [appleboy/ssh-action#225]
Hi,
One of our security tool identified an issue for this action.
"The Docker container is configured to run as the root user."
Can we run this container as a non-root user?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@tpatil30 Fixed in https://github.com/appleboy/ssh-action/releases/tag/v1.0.1 version.
