### ISSUE TITLE
tcp :22: connect: connection refused

### ISSUE THREAD

**Issue by RomuloPy** [appleboy/ssh-action#235]
Hello,
This is a YAML file I'm using for a flask app deployment on DigitalOcean.
I always get the error: "tcp :22: connect: connection refused"
Any tip please?

![image](https://user-images.githubusercontent.com/86781274/229117874-af76ab82-2a0d-491f-8aa0-7e9c4811bc3e.png)

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Please make sure your firewall setting and post your output log.

**Comment by appleboy** [comment]
This issue has been long-standing. I will close it for now. If there are similar problems in the future, please open a new issue.
