### ISSUE TITLE
Issue in build appleboy/ssh-action@master

### ISSUE THREAD

**Issue by nileena-ramesh** [appleboy/ssh-action#247]
Hi,

This step was working fine till few hours back. Now getting the following error:

> Build container for action use: '/home/runner/work/_actions/appleboy/ssh-action/master/Dockerfile'.
>Step 1/4 : FROM ghcr.io/appleboy/drone-ssh:1.6.13
>Head "https://ghcr.io/v2/appleboy/drone-ssh/manifests/1.6.13": Get "https://ghcr.io/token?scope=repository%3Aappleboy%2Fdrone->ssh%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
>Error: Docker build failed with exit code 1

Could you please help with this?

**Comment by MaxlineFeed** [comment]
> Head "https://ghcr.io/v2/appleboy/drone-ssh/manifests/1.6.13": Get "https://ghcr.io/token?scope=repository%3Aappleboy%2Fdrone-ssh%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Warning: Docker build failed with exit code 1, back off 3.841 seconds before retry.
/usr/bin/docker build -t 6c0442:36adafbbf60c4f1f8a[7](https://github.com/Maxline-Feed/feed-parsers/actions/runs/4818098393/jobs/8579708922#step:3:7)075e07159e72b -f "/home/runner/work/_actions/appleboy/ssh-action/master/Dockerfile" "/home/runner/work/_actions/appleboy/ssh-action/master"

same here

**Comment by Shennari** [comment]
> Head "https://ghcr.io/v2/appleboy/drone-ssh/manifests/1.6.13": Get "https://ghcr.io/token?scope=repository%3Aappleboy%2Fdrone-ssh%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Warning: Docker build failed with exit code 1, back off 3.841 seconds before retry.
/usr/bin/docker build -t 6c0442:36adafbbf60c4f1f8a[7](https://github.com/Maxline-Feed/feed-parsers/actions/runs/4818098393/jobs/8579708922#step:3:7)075e07159e72b -f "/home/runner/work/_actions/appleboy/ssh-action/master/Dockerfile" "/home/runner/work/_actions/appleboy/ssh-action/master"

same here

**Comment by YangsCalvin** [comment]
Me too

**Comment by Shennari** [comment]
https://www.githubstatus.com/incidents/vsc464zj7gv4

**Comment by lakshaygupta-simpplr** [comment]
This issue is happening for us as well.
 Step 1/4 : FROM ghcr.io/appleboy/drone-ssh:1.6.13
  Head "https://ghcr.io/v2/appleboy/drone-ssh/manifests/1.6.13": received unexpected HTTP status: 503 Service Unavailable

**Comment by kkartunov** [comment]
same

**Comment by namidad** [comment]
same here

**Comment by saikat449** [comment]
I am also getting some error

**Comment by Defterdar** [comment]
Same here

**Comment by AmalRichwin** [comment]
same here

**Comment by calvinsnax** [comment]
same here

**Comment by divya2424** [comment]
> Same here EDIT; Mine went through just now.

Yes

> This issue is happening for us as well. Step 1/4 : FROM ghcr.io/appleboy/drone-ssh:1.6.13 Head "https://ghcr.io/v2/appleboy/drone-ssh/manifests/1.6.13": received unexpected HTTP status: 503 Service Unavailable

It just worked for me now

**Comment by ibrahemid** [comment]
same here

**Comment by zhangsq-ax** [comment]
already working fine for us

```
Build container for action use: '/home/runner/work/_actions/appleboy/ssh-action/master/Dockerfile'.
  /usr/bin/docker build -t 6c0442:7***[1](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:1)338c66964980a5340[2](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:2)7990581491 -f "/home/runner/work/_actions/appleboy/ssh-action/master/Dockerfile" "/home/runner/work/_actions/appleboy/ssh-action/master"
  Sending build context to Docker daemon  [3](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:3)12.3kB
  
  Step 1/[4](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:4) : FROM ghcr.io/appleboy/drone-ssh:1.6.13
  1.6.13: Pulling from appleboy/drone-ssh
  f[5](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:5)[6](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:6)be85fc***e: Already exists
  e1c1ae1efe86: Pulling fs layer
  18402fbc4c4d: Pulling fs layer
  e1c1ae1efe86: Download complete
  18402fbc4c4d: Verifying Checksum
  18402fbc4c4d: Download complete
  e1c1ae1efe86: Pull complete
  18402fbc4c4d: Pull complete
  Digest: sha256:32deffb4c38aaa433065aad51[7](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:7)[8](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:8)575fa7651be6e13c757eb57f73d88aec75[9](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:9)1d
  Status: Downloaded newer image for ghcr.io/appleboy/drone-ssh:1.6.13
   ---> 1e003c3cb21c
  Step 2/4 : COPY entrypoint.sh /entrypoint.sh
   ---> 1775f6e6bf81
  Step 3/4 : RUN chmod +x /entrypoint.sh
   ---> Running in d449b86f543f
  Removing intermediate container d449b86f543f
   ---> ***ad8e605d1a
  Step 4/4 : ENTRYPOINT ["/entrypoint.sh"]
   ---> Running in 9b9840574a[10](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:10)
  Removing intermediate container 9b9840574a10
   ---> a9be35782761
  Successfully built a9be35782761
  Successfully tagged 6c0442:7***[13](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:13)38c66964980a53402799058[14](https://github.com/AutoxingTech/CSP-elevator-dispatcher-service/actions/runs/4818101345/jobs/8580826786#step:2:14)91
```

**Comment by kkartunov** [comment]
back to normal
