### ISSUE TITLE
issue with private ssh id_ed25519 key on ubuntu-latest

### ISSUE THREAD

**Issue by xavgru12** [appleboy/ssh-action#249]
https://github.com/xavgru12/ShopwareProduction/actions/runs/4850769808/jobs/8643979606

error message:
ssh.ParsePrivateKey: ssh: no key found

The key is existing

**Comment by appleboy** [comment]
See the documentation: https://github.com/appleboy/ssh-action#generate-ed25519-key

I can't reproduce the issue. Please post your YAML config and step to step instructions.

**Comment by appleboy** [comment]
This issue has been long-standing. I will close it for now. If there are similar problems in the future, please open a new issue.
