### ISSUE TITLE
dial tcp ***:***: connect: connection timed out

### ISSUE THREAD

**Issue by AnimeshRy** [appleboy/ssh-action#271]
Getting tcp timeout while connecting to my server. 

This is my workflow file
```
name: deploy
on:
  push:
    branches:
      - deploy-test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 200m
          debug: true
          script: whoami
```

I have all the keys present and can ssh fine but it's giving tcp time out in the action. No IP whitelisting on the server level, anybody can ssh into the server with the right creds. Not sure what is the issue here.

Have tried all the solutions in the duplicate issues and nothing worked at all.

**Comment by appleboy** [comment]
What is your os version? in Linode or AWS or somewhere you chose?

**Comment by AnimeshRy** [comment]
I think I found the reason for this. My server was blocked for all IPs other than the my country resulting in tcp timeouts. I was actually travelling abroad while I figured this out. It's a custom cloud provider.

Anyway I'll close the issue as this is not the action's fault
