### ISSUE TITLE
git pull denied on private repository

### ISSUE THREAD

**Issue by elprosdpp** [appleboy/ssh-action#273]
When i tried to do git pull from private repository i got errors like below
`err: git@github.com: Permission denied (publickey).
err: fatal: Could not read from remote repository.
err: Please make sure you have the correct access rights
err: and the repository exists.
`

But when i directly do git pull on server it works perfectly

It seems like I can't use other ssh key except id_rsa in docker inside ssh-action

I have done these folowing:
ssh-keygen -f ~/.ssh/myotherkey -t ed25519 -C "myotherkey"
ssh-add ~/.ssh/myotherkey 
cat ~/.ssh/myotherkey.pub (and then add it to ssh key https://github.com/settings/keys)
nano ~/.ssh/authorized_keys (add myotherkey.pub)

**Comment by appleboy** [comment]
See https://github.com/appleboy/ssh-action/issues/232#issuecomment-1506493783

**Comment by elprosdpp** [comment]
> See [#232 (comment)](https://github.com/appleboy/ssh-action/issues/232#issuecomment-1506493783)

if I use id_rsa,pub it works but when I use myotherkey.pub it doesn't work
