### ISSUE TITLE
Example of how to use this and get output of one or more lines to `$GITHUB_OUTPUT`

### ISSUE THREAD

**Issue by banagale** [appleboy/ssh-action#274]
I'm trying to look at the output from one of my multiline scripts in a follow up job or step. If a particular string is found, then the workflow set to fail.

Is there a way to use the relatively new methods for defining output parameters using `$GITHUB_OUTPUT`? ([docs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs))

If so, it would be great to see an example for `ssh-actions` including the `outputs` `id` and `needs` as in [this example](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job).

**Comment by appleboy** [comment]
@banagale I will take it.

**Comment by banagale** [comment]
Great, I have notifications turned on for this issue. Just lmk if i can test / review something.

**Comment by nelsonprsousa** [comment]
@appleboy Just out of curiosity, currently it is impossible to set some value from the bash (via SSH) to use on some other stage, right? Not sure if I am understanding this correctly.

Thank you!

**Comment by yaphet17** [comment]
@appleboy Can expect this feature soon?
