### ISSUE TITLE
Any security guarantee?

### ISSUE THREAD

**Issue by fchabouis** [appleboy/ssh-action#276]
Hi,
I have tested the tool and it is working fine.
I am wondering if there is an guarantee that my credentials won't be leaked. Of course keys are stored as Github secrets, but your code has access to the secrets and could possibly log them somewhere. I am probably not the first one with this concern, but I didn't find any information about such a risk.
Thanks!

**Comment by XXFOGS** [comment]
Same question

**Comment by bugohoss12** [comment]
Asked myself the same question recently. One option to mitigate the risk is, switching to self-hosted runners from Github. Setup an SSH-Key and add it to the known_hosts. Hereby you can avoid storing the private-key outside of the machine. See https://stackoverflow.com/a/72983036 .

**Comment by appleboy** [comment]
build docker image from here: https://github.com/appleboy/ssh-action/blob/4330a1ea489ced98a6778fb35bb6bfed8b61fca5/Dockerfile#L1

**Comment by appleboy** [comment]
We do not retain any credentials information. Once used, the Container is removed.
