### ISSUE TITLE
Server has NodeJS 16 active, but node -v returns version 12 from the github action.

### ISSUE THREAD

**Issue by khokonm** [appleboy/ssh-action#277]
Hi,
I've setup deploy automation for my newly created server. I initially installed node using `sudo apt install nodejs`, which installed the node version of 12.
Then I installed nvm and switched to node version 16.

Now, whenever I run `yarn install` or `node -v` from my SSH terminal. It works fine and return `v16.20.2`

But `yarn install` command from the github action returns the following output
```
out: yarn install v1.22.19
out: [1/4] Resolving packages...
out: [2/4] Fetching packages...
err: error firebase-admin@11.11.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.9"
out: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
err: error Found incompatible module.
```
For testing purpose, I added the `node -v` command in the action YML file, I got the following output 
```
out: v12.22.9
```

**Comment by binamralamsal** [comment]
I am also facing same issue

**Comment by khokonm** [comment]
Thanks a lot, it worked like charm!

**Comment by stepanjakl** [comment]
Or you could also add the same script to the `home/user/.profile`, which is read and executed with every log in.

For global configuration (applies to all users), the file is `/etc/profile`.
For individual user configuration, the file is `~/.bash_profile` or `~/.profile`.

> I am also facing same issue but my node.js version is coming v16.13.2 although I have v20 active on my VPS
> 
> Update: I fixed this issue by doing this:
> 
> ```yaml
> script: |
>   export NVM_DIR="$HOME/.nvm"
>   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
>   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
>   # your script here
> ```
> 
> Basically, it just make sures that v20 is active on your VPS. For some reasons, it doesn't get maintained.

**Comment by RapidoBots** [comment]
> I am also facing same issue but my node.js version is coming v16.13.2 although I have v20 active on my VPS
> 
> Update: I fixed this issue by doing this:
> 
> ```yaml
> script: |
>   export NVM_DIR="$HOME/.nvm"
>   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
>   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
>   # your script here
> ```
> 
> Basically, it just make sures that v20 is active on your VPS. For some reasons, it doesn't get maintained.

Thanks. It worked.

**Comment by rafaewaqarqazi** [comment]
Thanks

**Comment by appleboy** [comment]
See the same solution https://github.com/appleboy/ssh-action/issues/21#issuecomment-574050424
