### ISSUE TITLE
mvn: command not found

### ISSUE THREAD

**Issue by goldthree-shit** [appleboy/ssh-action#278]
This is my scripts;

`- name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/myapp-docker-compose/myapp
          git pull origin dev 
          mvn package -Dmaven.test.skip=true 
          cd .. 
          docker rm -f myappy 
          docker rmi myapp:latest 
          docker-compose up -d  myapp
`
While running to the third step `mvn` will encountered the exception mvn: command not found.
But I am sure that my pc exist maven and run command `maven -v` could show the version.
What should I do., thank you

**Comment by appleboy** [comment]
@goldthree-shit Please export your path first and check what's happen.

**Comment by goldthree-shit** [comment]
> @goldthree-shit Please export your path first and check what's happen.

Thank you,  useful.
`
 export PATH="/home/softwares/jdk-17.0.8/bin:$PATH"
export PATH="/home/softwares/maven3.8.8/bin:$PATH"
`

**Comment by appleboy** [comment]
@goldthree-shit So resolve your problem? Can you close the issue?
