### ISSUE TITLE
Should I allow all IP for ssh?

### ISSUE THREAD

**Issue by copyNdpaste** [appleboy/ssh-action#282]
I'm using AWS linux ec2.

I'm allowing only specific IPs on security group.

It is hard to allow all IP for ssh-action.

Are there other solutions?

**Comment by copyNdpaste** [comment]
If I use `authorize-security-group-ingress` on workflow, then should I remove IP on security group that connected ec2 always?

**Comment by appleboy** [comment]
https://github.com/orgs/community/discussions/26442
