### ISSUE TITLE
Not running on self-hosted

### ISSUE THREAD

**Issue by infomegmagaming** [appleboy/ssh-action#29]
##[error]File not found: 'docker'

**Comment by appleboy** [comment]
your server must be provided with the docker environment.

**Comment by infomegmagaming** [comment]
What if I don't want to use docker? I just want to SSH into and execute scripts on my server.

**Comment by MartinPavlik** [comment]
Would be nice to write this to the docs, because I just spent ~20 minutes investigating the same problem :cry:

**Comment by appleboy** [comment]
@MartinPavlik Sorry, I will update the documentation.

**Comment by appleboy** [comment]
@MartinPavlik Add notes in readme:

> Importment: Only support Linux docker container.
