### ISSUE TITLE
docker: Error response from daemon: Mounts denied: 

### ISSUE THREAD

**Issue by NguyenVanHung24** [appleboy/ssh-action#291]
![image](https://github.com/appleboy/ssh-action/assets/92856026/d3e7c63a-f06b-4f9c-a52a-98efc1b42fdd)
I run this action but i have bug like this and i don't know how to fix it. 
![image](https://github.com/appleboy/ssh-action/assets/92856026/b2ff980b-07c0-48ca-98d7-6286508238cf)

**Comment by appleboy** [comment]
Please restart the task again. This doesn't seem to be an issue with the ssh-action.

**Comment by NguyenVanHung24** [comment]
Oh, i think because i run github action on my runner docker.
