### ISSUE TITLE
Using username and password getting ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

### ISSUE THREAD

**Issue by nishwalshetty** [appleboy/ssh-action#294]
we dont have a domain, so i want to use ip address of the server instead of hostname

is this possible ?

      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 10.10.11.x
          username: ${{ steps.secrets.outputs.LINUX_SERVER_USERNAME }}
          password: ${{ steps.secrets.outputs.LINUX_SERVER_PASSWORD }}
          port: 22  # Replace with your server's SSH port

i tried the above didnt work

getting error

2024/02/05 09:59:39 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

i have enabled PasswordAuthentication yes in configuration

**Comment by real-F-00** [comment]
i'm sorry but how did you fix this problem?
