### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by khang-digitaliron** [appleboy/ssh-action#298]
![image](https://github.com/appleboy/ssh-action/assets/158536560/1a109ef6-12be-4ddb-97bf-68b0dcd89552)
I just got this issue without error logging. Please help me!

**Comment by sunvim** [comment]
it seems to not set ssh pub key on the remote server

**Comment by khang-digitaliron** [comment]
I had added public key to `authorized_keys` on my server.

**Comment by appleboy** [comment]
@khang-digitaliron Try password solution and move to https://github.com/appleboy/ssh-action/issues/297 for furthur discussion.

**Comment by phpmac** [comment]
Use `fifsky/ssh-action@master` to solve my problem,
