### ISSUE TITLE
can't connect without a private SSH key or password

### ISSUE THREAD

**Issue by andersonalz** [appleboy/ssh-action#318]
Run appleboy/ssh-action@master
  with:
    host: *****
    username: root
    port: ******
    command_timeout: 2000m
    script: cd /var/www/*****
  git checkout demo
  git pull
  docker compose down            
  docker compose up -d --build
  
    protocol: tcp
    timeout: 30s
    proxy_port: 22
    proxy_timeout: 30s
Run echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
Run entrypoint.sh
Will download drone-ssh-1.7.4-linux-amd64 from https://github.com/appleboy/drone-ssh/releases/download/v1.7.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 5580k  100 5580k    0     0  39.9M      0 --:--:-- --:--:-- --:--:-- 39.9M
2024/04/28 12:33:02 Error: can't connect without a private SSH key or password
Error: Process completed with exit code 1.

**Comment by appleboy** [comment]
```yaml
host: *****
username: root
port: ******
```

missing password or raw key?

**Comment by andersonalz** [comment]
> ```yaml
> host: *****
> username: root
> port: ******
> ```
> 
> missing password or raw key?

yes my password was wrong
