### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by adm-dev** [appleboy/ssh-action#32]
i can't connect to my server. having `dial tcp ***:22: i/o timeout` error

**Comment by izshreyansh** [comment]
Can you share how did you solve it? @adm-dev

**Comment by nwesber** [comment]
Hi @izshreyansh,

I solved the problem by adding correct keys in both my repository and server for proper exchange.

**Comment by appleboy** [comment]
Please see the document https://github.com/appleboy/ssh-action#setting-up-ssh-key before using the plugin.

**Comment by GarryOne** [comment]
In my case, it was a conflict because I was declaring to use it for the Node app, while this was affecting the `ssh-action`. 
```
env:
  PORT: 8000
```

The solution was to rename the variable from `PORT` to `APP_PORT`.

**Comment by agm1984** [comment]
We just had this error and it was caused by the server IP changed but the old IP was hardcoded into GitHub actions.

**Comment by kadriev-ilyas** [comment]
> In my case, it was a conflict because I was declaring to use it for the Node app, while this was affecting the `ssh-action`.
> 
> ```
> env:
>   PORT: 8000
> ```
> 
> The solution was to rename the variable from `PORT` to `APP_PORT`.

You saved my day! Thank you:)

**Comment by ralyodio** [comment]
adding `debug: true` doesn't do anything. I'm also getting timeout error. rsync works fine but ssh-action module does not connect using same params.

**Comment by GarryOne** [comment]
> adding `debug: true` doesn't do anything. I'm also getting timeout error. rsync works fine but ssh-action module does not connect using same params.

You can temporarily fork the repository, use your version and add more logging for debugging it easier. I did the same.

**Comment by tanakorn0314** [comment]
> In my case, it was a conflict because I was declaring `PORT` env var for the Node app, while this was affecting the `ssh-action`.
> 
> ```
> env:
>   PORT: 8000
> ```
> 
> The solution was to rename the variable from `PORT` to `APP_PORT`.

Save my day !!!!

**Comment by PajaroConnect2BPO** [comment]
> We just had this error and it was caused by the server IP changed but the old IP was hardcoded into GitHub actions.
I had the same issue, thank you very much

**Comment by nelajc** [comment]
@appleboy isn't this issue regarding server security group limited to specific  IPs ? for example our server can only access using our ip address. if so can help which ip ranges should i whitelist to our server? thanks

```
======CMD======
sudo docker ps
======END======
2024/01/31 10:58:54 dial tcp ***:22: i/o timeout
```

**Comment by appleboy** [comment]
@nelajc Please see the discussion https://github.com/orgs/community/discussions/26442

**Comment by SafwatImran** [comment]
> In my case, it was a conflict because I was declaring `PORT` env var for the Node app, while this was affecting the `ssh-action`.
> 
> ```
> env:
>   PORT: 8000
> ```
> 
> The solution was to rename the variable from `PORT` to `APP_PORT`.

Thanks a lot! This worked for me after hours of trying to debug the issue!

**Comment by superpollo2** [comment]
I have the same issue. This is my job.

        name: Deploy and Run Docker Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          
          
And the error remains the same:
======END======
2024/03/29 04:05:00 dial tcp ***:22: i/o timeout

I'm not sure if it's related to the port, but I don't see why it would be. I'm trying to access a server that belongs to me.
II have one last question, in the SSH_KEY should I put the private key I have on my server, right?

**Comment by lasaaliceblue** [comment]
I am also facing the same issue.

**Comment by steve-jr** [comment]
@appleboy The remote server is supposed to whitelist Github actions IPs
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses
