### ISSUE TITLE
how can i mask commands run in host

### ISSUE THREAD

**Issue by salahhusa9** [appleboy/ssh-action#329]
how can i mask this
```
======CMD======
whoami
...
======END======
```

**Comment by appleboy** [comment]
I will take it. By default, the above message will be hidden. If Debug mode is enabled, it will be displayed.

**Comment by appleboy** [comment]
try the master version `appleboy/ssh-action@master`

**Comment by salahhusa9** [comment]
he don't work, it's output more infos
