### ISSUE TITLE
URl Download

### ISSUE THREAD

**Issue by TheProzin** [appleboy/ssh-action#331]
Hi there. I have been using your project for some time now, and it has been very helpful. However, I believe that due to some recent updates, the download URL is incorrect.

![image](https://github.com/user-attachments/assets/089c47a7-3d45-4df5-97f2-3ce3dba6f99f)

When it was at v1.7.4, it executed correctly:

![image](https://github.com/user-attachments/assets/9920696a-9586-4091-9d7f-71312c929ef1)

But now, in v1.7.7, it doesn't:

![image](https://github.com/user-attachments/assets/129bb324-d920-43b7-a5c2-4bffde08d24e)

And when trying to access the URL, it goes to a 404 error:

**Comment by appleboy** [comment]
@TheProzin I think it is not an issue. Your command has been executed successfully.

<img width="998" alt="image" src="https://github.com/user-attachments/assets/6095570d-43c5-4ab1-9091-2b61ab459355">
