### ISSUE TITLE
SSH Handshake Failed Multiple times

### ISSUE THREAD

**Issue by rajpatel2435** [appleboy/ssh-action#333]
`
name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.1'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build:production

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Clean existing theme files
          rm -rf /var/www/html/wp-content/themes/betseige

          # Copy new theme files
          scp -r dist/ ${GITHUB_ACTOR}@${{ secrets.DIGITALOCEAN_HOST }}:/var/www/html/wp-content/themes/betseige
`

![image](https://github.com/user-attachments/assets/3b0e214b-654c-4eed-9dac-7dededa3015c)

Can anyone help me with this?

Thanks

**Comment by ibnahzab** [comment]
Yes I confirm I got this error too.

**Comment by rajpatel2435** [comment]
Hi there, 

I got the solution here for my case

Just change the version for ssh action to ssh-action@v0.1.3

That is solved my error.

Thanks
