### ISSUE TITLE
SSH Action downloads corrupt/incorrect dependency

### ISSUE THREAD

**Issue by alvin-soo-ad** [appleboy/ssh-action#334]
Action is pointing to: `https://github.com/appleboy/drone-ssh/releases/download/v1.7.7` for the executable, which is no longer valid. It should now point to `https://github.com/appleboy/drone-ssh/releases/v1.7.7`

Probable relevant file: https://github.com/appleboy/ssh-action/blob/b4a07ca5940a7dc94925e99f8e6eab3671b0fa64/entrypoint.sh#L10

Screenshot: 
![image](https://github.com/user-attachments/assets/47d1b5da-3346-4fc8-a244-dd16d2b5b235)

**Comment by alvin-soo-ad** [comment]
Apologies, issue seems to be different than originally thought. Link is correct, but downloaded file seems to be corrupted or in incorrect format.

**Comment by bradhead** [comment]
I get a 404 not found on that Url. The appleboy/ssh-action@v1.0.3 is essentially broken now.
