### ISSUE TITLE
No common Algorithm

### ISSUE THREAD

**Issue by zaguerinho** [appleboy/ssh-action#36]
While connecting to a ssh server I get the following message? any conf or server side config/tweak to be made? 

Regards

> 2020/02/28 00:38:25 ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group-exchange-sha256]

**Comment by appleboy** [comment]
See the reference: https://github.com/golang/go/issues/20201

**Comment by appleboy** [comment]
Please try the ssh-action@v0.0.9 version. See https://github.com/appleboy/ssh-action/releases/tag/v0.0.9
