### ISSUE TITLE
Failure of a command result in a successful action

### ISSUE THREAD

**Issue by ArchangelX360** [appleboy/ssh-action#42]
## Observed behaviour
Even if a command failed, the action is having a successful output.

## Expected result
Action should fail in my opinion, what do you guys think?

## Screenshot
![image](https://user-images.githubusercontent.com/4418480/77857646-099b6700-71ff-11ea-90f8-26d81fc5894f.png)

**Comment by appleboy** [comment]
Add `script_stop: true`

**Comment by ArchangelX360** [comment]
My bad, indeed.

Shouldn't it be the default though?
So far, pipeline products I have used are running there script with `set -e` as default.
