### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by manivel-nagarajan** [appleboy/ssh-action#45]
I'm not able to use this in my workflow file since that runs on macOS. Please consider supporting macOS.

**Comment by appleboy** [comment]
It also works in macOS. Please provide the detailed logs or instructions.

**Comment by manivel-nagarajan** [comment]
Thank you for the response.

Please find the attached logs and code snippets that I've used in the workflow file.

<img width="458" alt="Screenshot 2020-04-11 at 11 37 21 PM" src="https://user-images.githubusercontent.com/54974141/79051403-b89f6000-7c4d-11ea-9c9d-49f84df9ac86.png">

<img width="497" alt="Screenshot 2020-04-11 at 11 36 44 PM" src="https://user-images.githubusercontent.com/54974141/79051381-973e7400-7c4d-11ea-8943-bdf57657f6bc.png">

Please advice if my configuration is wrong.

**Comment by FDiskas** [comment]
change to `runs-on: ubuntu-latest`

**Comment by appleboy** [comment]
@manivel-nagarajan Sorry my bad. This plugin only run on Linux OS.
