### ISSUE TITLE
Error: missing host server

### ISSUE THREAD

**Issue by ldicarlo** [appleboy/ssh-action#47]
So in case anyone, like I did, bumps into this error, it might be because you're using the version given by default by github (v0.0.2) which, I guess, didn't support the env variables correctly.
What I did was simply updating:
`uses: appleboy/ssh-action@v0.0.2`
to
`uses: appleboy/ssh-action@master`
Though I guess using other tags will work also. 
Thanks for the Action btw !

**Comment by JZLeung** [comment]
thx.
i think you can mention a pr.

**Comment by ldicarlo** [comment]
I'm not sure what you mean. 
I suppose, when deploying an action to Github, at some point you must select the tagged version you want to mark as 'latest', and I think the author didn't mark the last one, resulting in these screens: 
![image](https://user-images.githubusercontent.com/15803534/79831545-e8660a80-83a7-11ea-99a5-fdff1cd5e65f.png)
_default selected version_


![image](https://user-images.githubusercontent.com/15803534/79831585-f7e55380-83a7-11ea-99a2-aa3f2b2411fd.png)
_other possible versions_

**Comment by appleboy** [comment]
Please try the latest version in https://github.com/marketplace/actions/ssh-remote-commands

**Comment by ldicarlo** [comment]
I understand that you did two Github actions for that, but when searching for "ssh" in Github marketplace, https://github.com/marketplace?type=actions&query=ssh, this action is the first result. 
![image](https://user-images.githubusercontent.com/15803534/80274158-af47d600-86d8-11ea-814f-fd73e3aef83f.png)
While the second action that you're mentioning is the 15th. 
Couldn't you:
- mark this action as deprecated, or
- add a link in this action to the new one in the description, or
- merge the two in only one action ? 

That said, again, thanks, it works nicely, I fully satisfied using that for my personal CD.

**Comment by appleboy** [comment]
I deleted the old one and it can't work to rename the `SSH Execute Commands` to `SSH Commands`. I created a ticket to GitHub contact.
