### ISSUE TITLE
Shold `port` has a default value 22 ?

### ISSUE THREAD

**Issue by jerrybendy** [appleboy/ssh-action#5]
Hi,
I got an error with the latest version:

```
2019/09/30 08:11:32 could not parse  as int value for flag port,p: strconv.ParseInt: parsing "": invalid syntax
```

Is it better to give `port` a default value?

**Comment by ggarcz1** [comment]
what was the resolution to this issue?

**Comment by rogyar** [comment]
Please note that you may get this error if you have specified a non-existent secret in your workflow (i.e., incorrect secret name for port)
