### ISSUE TITLE
Unable to execute valid pm2 command

### ISSUE THREAD

**Issue by leJOEndary** [appleboy/ssh-action#51]
I am using the action to:

- cd to project directory (Success)
- pull the latest code from master on my repo (Success)
- Restart the pm2 deployment using "pm2 restart app" (Failure)

err: bash: line 2: pm2: command not found

I'm pretty sure pm2 is working well on my server. Does the action use a sub process that doesn't have all the dependencies?

**Comment by appleboy** [comment]
See https://github.com/appleboy/ssh-action/issues/44
