### ISSUE TITLE
Unable to run deployment server specific commands

### ISSUE THREAD

**Issue by daukadolt** [appleboy/ssh-action#55]
I am trying to use commands like "npm install", "pm2 restart",
but action fails:

```
err: bash: line 3: npm: command not found
err: bash: line 4: pm2: command not found
```

I am using nvm on the server, and thought that it might be the path resolution issue.
However, even using the absolute path, hardcoded, did not help:

```
err: /usr/bin/env: ‘node’: No such file or directory
err: /usr/bin/env: ‘node’: No such file or directory
```

**Comment by makivlach** [comment]
What did you do to solve this issue?
