### ISSUE TITLE
Executing remote ssh commands failing

### ISSUE THREAD

**Issue by invinciblemuffi** [appleboy/ssh-action#60]
```
- name: Deploy to ${{ secrets.HOST }}, executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with: |
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        script: ~/deploy.sh
        key_path: ${{ secrets.DEPLOY_KEY }}
```

When GitHub action starts it fails on below error.

##[error]The template is not valid. .github/workflows/main.yml (Line: 28, Col: 13): Unexpected value 'username: ***

**Comment by vashov** [comment]
Hello. 
A mistake is in row "with: |" in this yaml script. No symbol "|" needed.

>       with:
>         username: ${{ secrets.USERNAME }}
>         host: ${{ secrets.HOST }}
>         script: ~/deploy.sh
>         key_path: ${{ secrets.DEPLOY_KEY }}

**Comment by Hatimtech** [comment]
```
 Deploy to ***, executing remote ssh commands using ssh key 2s
1
Run appleboy/ssh-action@master
2
  with:
3
    username: ***
4
    host: ***
5
    script: ~/deploy.sh
6
    key_path: ***
7
    port: 22
8
    sync: false
9
    use_insecure_cipher: false
10
    timeout: 30s
11
    command_timeout: 10m
12
    proxy_port: 22
13
    proxy_timeout: 30s
14
    proxy_use_insecure_cipher: false
15
    script_stop: false
16
    debug: false
17
/usr/bin/docker run --name d3cd1d467000ee4119858ed9100a1e0ce6_b0677c --label 3888d3 --workdir /github/workspace --rm -e INPUT_USERNAME -e INPUT_HOST -e INPUT_SCRIPT -e INPUT_KEY_PATH -e INPUT_PORT -e INPUT_PASSPHRASE -e INPUT_PASSWORD -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v 
Deploy to ***, executing remote ssh commands using ssh key 2s
======CMD======
19
~/deploy.sh
20
======END======
21
2020/06/02 03:40:33 getKeyFile error: open ***
71
***: no such file or directory
72
2020/06/02 03:40:34 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

I have put deploy.sh file in home directory of server where it will execute sudo su command and go that directory where my build will be pulled.

deploy.sh
```
sudo su <<HERE
ls /var/www/<PROJECT-NAME>
HERE
```

I am unable to get the error here, whether above it is not able to find deploy.sh or my privateKeyFile stored in secrets.

**Comment by invinciblemuffi** [comment]
```
 Deploy to ***, executing remote ssh commands using ssh key 2s
1
Run appleboy/ssh-action@master
2
  with:
3
    username: ***
4
    host: ***
5
    script: ~/deploy.sh
6
    key_path: ***
7
    port: 22
8
    sync: false
9
    use_insecure_cipher: false
10
    timeout: 30s
11
    command_timeout: 10m
12
    proxy_port: 22
13
    proxy_timeout: 30s
14
    proxy_use_insecure_cipher: false
15
    script_stop: false
16
    debug: false
17
/usr/bin/docker run --name d3cd1d467000ee4119858ed9100a1e0ce6_b0677c --label 3888d3 --workdir /github/workspace --rm -e INPUT_USERNAME -e INPUT_HOST -e INPUT_SCRIPT -e INPUT_KEY_PATH -e INPUT_PORT -e INPUT_PASSPHRASE -e INPUT_PASSWORD -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v 
Deploy to ***, executing remote ssh commands using ssh key 2s
======CMD======
19
~/deploy.sh
20
======END======
21
2020/06/02 03:40:33 getKeyFile error: open ***
71
***: no such file or directory
72
2020/06/02 03:40:34 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

I have put deploy.sh file in home directory of server where it will execute sudo su command and go that directory where my build will be pulled.

deploy.sh
```
sudo su <<HERE
ls /var/www/<PROJECT-NAME>
HERE
```

I am unable to get the error here, whether above it is not able to find deploy.sh or my privateKeyFile stored in secrets.

**Comment by vashov** [comment]
> 21
> 2020/06/02 03:40:33 getKeyFile error: open ***
> 71
> ***: no such file or directory
> 72
> 2020/06/02 03:40:34 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

Looks like wrong **key_path**.
I guess, that **key_path** is path in your repository, for example:
`key_path: ./folder_in_your_repository/id_rsa`

But if you want use **key_path**, then ssh private key must be in your repository.
I think this is a _**bad idea**_.

It may be better to use **password** or **key** of user instead of **key_path**.

### Use password of user
I guess you have `root` user on server.
Set password for 'root'. 
https://askubuntu.com/questions/155278/how-do-i-set-the-root-password-so-i-can-use-su-instead-of-sudo

Save github secrets:
USERNAME = root
PASSWORD = root_password

Then use secrets in actions yaml
```
with:
    username: ${{ secrets.USERNAME }}
    host: ${{ secrets.HOST }}
    script: ~/deploy.sh
    password: ${{ secrets.PASSWORD}}
```

### Or use ssh private key of user
Just save content of your private key in github secrets.
PRIVATE_KEY = content_of_your_keyFile_eg_id_rsa

Then use secrets in actions yaml
```
with:
    username: ${{ secrets.USERNAME }}
    host: ${{ secrets.HOST }}
    script: ~/deploy.sh
    key: ${{ secrets.PRIVATE_KEY }}
```

I didn't use variant with private key, but it must work.

**Comment by invinciblemuffi** [comment]
I already have Private key in github secrets. I have also change KEY_PATH to KEY only. 

Username is XXXXX for logging in to server. After that i want that script to run(deploy.sh) which I had pasted above to go and do sudo su so I can access my project and then deploy the build there.

======CMD======
19
~/deploy.sh
20
======END======
21
2020/06/02 09:19:52 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by vashov** [comment]
Do you set ssh public key on server?
https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1604

**Comment by invinciblemuffi** [comment]
I followed this documentation to generate public/private key value pair on my server: https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by vashov** [comment]
Check this link, may be it will help
https://askubuntu.com/questions/46424/how-do-i-add-ssh-keys-to-authorized-keys-file

**Comment by invinciblemuffi** [comment]
In step 3 of https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1604, I cannot login using `ssh username@remote_host` as normally I login to server using this `ssh -i filename.pem username@hostname`.

**Comment by invinciblemuffi** [comment]
I was able to finally add private key to my github and also add it to server using `eval $(ssh-agent)` then `chmod 600 <PRIVATEKEYFILENAME.pem>` then  `ssh-add <PRIVATEKEYFILENAME.pem>`. 
I was able to successfully login to server using apple-boy ssh-action and also execute script on server. To execute the script we will have to do `chmod +x <SCRIPTFILENAME.sh>`.

**Comment by TechQuery** [comment]
I fix this by migrating to https://github.com/garygrossgarten/github-action-ssh
