### ISSUE TITLE
Not Working in self hosted runner

### ISSUE THREAD

**Issue by jaswanth098** [appleboy/ssh-action#61]
I have installed docker and tried this it is throwing the following error
```
/usr/bin/docker build -t 848848:ae2915a552543c4284c07636defa0be9 -f "/home/action/actions-runner/_work/_actions/appleboy/ssh-action/master/Dockerfile" "/home/action/actions-runner/_work/_actions/appleboy/ssh-action/master"
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=d251v9oyc8txdzjtdjwmhcp5d&shmsize=0&t=848b6a%3Aae2015f558544c4284c07636deef0be9&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
```

is there a way to say I need to run the docker with sudo?

**Comment by appleboy** [comment]
Please check the Linux user's permission.

**Comment by jaswanth098** [comment]
I used `sudo usermod -aG docker action` to allow my self-hosted user to have access to docker without sudo even then it is not working

**Comment by jaswanth098** [comment]
After some digging understood that this is a problem from GitHub
In Github action.yml we just specify docker and DockerFile and GitHub runner itself will create the command for building the image and running the image 
closing this issue

**Comment by appleboy** [comment]
@jaswanth098 Can you show the action.yml?

**Comment by jaswanth098** [comment]
I was talking about your action.yml itself you did not write the command for docker build and docker run right it is being generated by GitHub runner itself

**Comment by appleboy** [comment]
@jaswanth098 OK. I got your point.
