### ISSUE TITLE
security concerns

### ISSUE THREAD

**Issue by vesparny** [appleboy/ssh-action#66]
Is there any way to mitigate the risk of uploading SSH private keys to GitHub.
I know they are encrypted but they could potentially give full access to the server.

thanks

**Comment by KerberosMorphy** [comment]
You could use AWS Secrets Manager or Parameters Store or any other service and import your SSH private key before using it.

**Comment by appleboy** [comment]
Please create a deploy account and don't grant the root permission.

**Comment by krystalflame** [comment]
> Please create a deploy account and don't grant the root permission.

What do you mean by this? I want to make sure this is as secure as possible before I set this up.

**Comment by appleboy** [comment]
Put your public key into `deploy` account so you only have the permission of deploy user in the server.

**Comment by krystalflame** [comment]
Oh, ok. This is probably the wrong place to ask, but do you know of a way to make that user only able to use a specific set of commands?

**Comment by appleboy** [comment]
@krystalflame Please see the docs: https://access.redhat.com/solutions/65822

**Comment by appleboy** [comment]
This is not `ssh-action` issue. I will close the issue
