### ISSUE TITLE
Job hangs until timeout if command starts a program that doesn't finish

### ISSUE THREAD

**Issue by ragnarak54** [appleboy/ssh-action#67]
I'm trying to use this as a way to update a continuously running Python application on my remote server. The sequence of commands I'd like to run is:
```
pkill -f 'python filename.py'
git pull
nohup python filename.py &
```
This all works fine, and the entire process executes successfully. However, the Github job will say that the action step is pending until the timeout limit is reached, at which point it "fails." With a Python script that runs and finishes, the job correctly succeeds and finishes. I thought it may have been because the Python script didn't exit, which made it think I could have more commands waiting to be executed afterward, which is why I added the nohup. Unfortunately, no combination of running in the background and additional commands after running the file (which also successfully execute) has made the Github job realize that it is finished.

**Comment by alelevinas** [comment]
same issue here

**Comment by flancer64** [comment]
@ragnarak54 , try this:
```
nohup python filename.py > ./output.log 2>&1 &
```

**Comment by PKlempe** [comment]
@flancer64 
> ```
> nohup python filename.py > ./output.log 2>&1 &
> ```

This worked perfectly. Thank you very much! ❤

**Comment by appleboy** [comment]
I think this issue should be closed. Thanks.

**Comment by Ciel-azure** [comment]
@flancer64 perfectly work. thank you !!

**Comment by Ciel-azure** [comment]
@flancer64 perfectly work. thank you !!
