### ISSUE TITLE
Mask secrets properly

### ISSUE THREAD

**Issue by mittalyashu** [appleboy/ssh-action#68]
I am not sure if this is issue from the GitHub server side or the package itself, but it doesn't mask the secrets properly.

<img width="178" alt="Screenshot 2020-07-08 at 10 01 44 AM" src="https://user-images.githubusercontent.com/29014463/86876663-da9c6780-c102-11ea-9f00-5f9d24f90b36.png">

at few places it mask the secrets where it is not required.

<img width="1136" alt="Screenshot_2020-07-08_at_10_07_56_AM" src="https://user-images.githubusercontent.com/29014463/86877003-92ca1000-c103-11ea-9be1-ca7f32b4673d.png">

**Comment by appleboy** [comment]
@mittalyashu This is a GitHub's problem.
