### ISSUE TITLE
is key_path really implemented

### ISSUE THREAD

**Issue by mkungla** [appleboy/ssh-action#8]
is `key_path: $GITHUB_WORKSPACE/.ssh/id_rsa` possible?

**Comment by appleboy** [comment]
Yes, you can try it.

**Comment by EGSatelix** [comment]
it does'nt work for me...

> getKeyFile error: open PATH/MYKEY: no such file or directory

It's weird, script works with scp-action

**Comment by ocratravis** [comment]
I'm having the same issue. I've tried both of the following:

key_path: ~/.ssh/mypublickey
key_path: $GITHUB_WORKSPACE/.ssh/mypublickey

The file is definitely there, because a previous step (an scp command) is able to find it at ~/.ssh/mypublickey.
