### ISSUE TITLE
IP fixo ao deploy no servidor

### ISSUE THREAD

**Issue by naruto112** [appleboy/ssh-action#82]
Boa tarde,
Estou com um dúvida no script do appleboy.
Quando eu executo um push no github existe um workflow que escuta minha branch developer e começa a rodar alguns steps na qual executo pra enviar para o servidor desejado. O problema é que quando eu executo um push a maquina criada no github ela conecta por um IP que eu forneço e ela conecta por IP que a github gera... só que toda vez que eu executo o push ela executa o processo de steps do workflow ela gera um novo IP e pra mim que trabalha em uma rede com firewall alto é problema por que nunca executa o mesmo IP. Alguém já passou por isso e conseguiu solucionar ?

**Comment by appleboy** [comment]
Please speak in English.
