### ISSUE TITLE
what is the ip range to whitelist 

### ISSUE THREAD

**Issue by gitdckap** [appleboy/ssh-action#87]
Hi,
We have successfully deployed to our gihub action, We have whitelisted for the SSH port no for our server,
could you please provide the ip ranges, and please provide the port no to whitelist.
we can whitelist in our server. because we do not want open the ssh port 22 globally.

**Comment by gitdckap** [comment]
hi,
can you please let know
any update regarding this,

**Comment by appleboy** [comment]
You can change the port directly. See the readme https://github.com/appleboy/ssh-action#input-variables

**Comment by gitdckap** [comment]
I understand we can change the port no 
is it possible to access using whitelisted ip,
do you have any ip to whitelist, please let me know.
