### ISSUE TITLE
Permission denied issue

### ISSUE THREAD

**Issue by RaduCStefanescu** [appleboy/ssh-action#88]
We are using the `ssh-action` in one of our deployment actions.
The action fails with the following output:

```
======CMD======
/root/deploy/restart.sh
======END======
2020/10/23 11:43:23 Process exited with status 126
err: bash: /root/deploy/restart.sh: Permission denied
```

Here is the code for the action: https://github.com/code4romania/rezultate-vot-api/blob/develop/.github/workflows/build-stage.yml

Does the script need to be copied over on the machine where we want to run it?

**Comment by gitdckap** [comment]
may i know your ssh username,, are you connected with root user account

**Comment by RaduCStefanescu** [comment]
The issue was fixed, it seems the script needs to reside on the machine where we want to run it.
