### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by noob-master147** [appleboy/ssh-action#96]
# ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

This is my workflow file
what i am trying to do with this action is on pushing to master
* create a docker image
* push the docker image to docker hub
* ssh into my AWS EC2 server
* run a set of instruction to update the docker image

```name: Feedachild Client

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - name: Build the React Docker Image
      run: |
        docker build . --file Dockerfile --tag noobmaster147/feedachild-frontend
    - name: Docker push 
      run: |
        docker push noobmaster147/feedachild-frontend
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          pwd
          ls -la
          docker-compose down
          docker-compose pull
          docker-compose up --build -d
```

I am stuck with this issue for hours now. 

![image](https://user-images.githubusercontent.com/43108912/99870917-9a92d880-2bfc-11eb-932b-a2ac59914174.png)

the pem file that I am using was generated by aws, in the process of creating an instance

this is the command I use to ssh from my laptop ```ssh -i ~/Documents/feedachild.pem ubuntu@ec2-*-**-***-***.us-east-2.compute.amazonaws.com```

therefore the secrets I added were
HOST => ```ec2-*-**-***-***.us-east-2.compute.amazonaws.com```
PORT => 22
USERNAME => ubuntu
KEY => pasted the RSA Key as it is

**Comment by appleboy** [comment]
duplicated of #80

**Comment by Yaqoob-Aslam** [comment]
I am getting same error how Can I resolve this Issue "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"

**Comment by appleboy** [comment]
@Yaqoob-Aslam Do you refer to https://github.com/appleboy/ssh-action#setting-up-a-ssh-key guide?

**Comment by shylock-wu** [comment]
Is this the file in the aws server?

**Comment by nhastor1** [comment]
In case of administrative user on windows, you need to add your public key into file named `administrators_authorized_keys` in `C:\ProgramData\ssh\`.

**Comment by ct123-cmd** [comment]
You only need to authorise your key

`cat id_rsa.pub >> authorized_key`

**Comment by syntaxlexx** [comment]
> You only need to authorize your key
> 
> `cat ~/.ssh/id_rsa.pub >> authorized_key`

It's funny how something as trivial as this can keep one awake at night! Kuddos!

**Comment by sugurugojow** [comment]
@syntaxlexx  where do i have to put this in my local or my ec2 instance ?

**Comment by ct123-cmd** [comment]
This is just a way to connect using SSH, it depends on your requirements. 
what is your purpose, building a CI/CD pipeline or a code pipeline from local to github or somehwere

**Comment by sugurugojow** [comment]
for ci/cd pipeline

**Comment by ct123-cmd** [comment]
This is something need to check from start to end, but what I can see in your error logs, you did something wrong with your key files, and that's why your are not able to  push the code

**Comment by Mfonn** [comment]
> > You only need to authorize your key
> > `cat ~/.ssh/id_rsa.pub >> authorized_key`
> 
> It's funny how something as trivial as this can keep one awake at night! Kuddos! `cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys`

This worked for me!!!

**Comment by gerlynm** [comment]
ssh is different to sshd. Make sure you have set PasswordAuthentication to yes in the SSHD file, and restarted the sshd service.

**Comment by ucodefusion** [comment]
Step 1 
![image](https://github.com/appleboy/ssh-action/assets/655131/6fc25e28-5dbe-476c-953e-24ca505abfa1)
Add this values to github , 

If you not sure what it is 
SERVER_IP your server ip `ping your_server_domain.com`
SERVER_USER  `AWS EC2, DigitalOcean, or Azure, the default username will be ubuntu. If you're using a different   or a custom setup, the default user might be root, ec2-user (for Amazon Linux), `
SSH_PRIVATE_KEY your server private key  `cat ~/.ssh/id_rsa`

Step 2

cat ~/.ssh/id_rsa.pub >> authorized_key

Step 3 Run your pipeline

**Comment by seniorpung** [comment]
when I access cPanel using ssh client, I got this error.
How to handle this error?

**Comment by yashrahurikar23** [comment]
> You only need to authorize your key
> 
> `cat ~/.ssh/id_rsa.pub >> authorized_key`

This worked for me. although it is cat ~/.ssh/id_rsa.pub >> authorized_keys not cat ~/.ssh/id_rsa.pub >> authorized_key

**Comment by Vinc135** [comment]
I tried everything above and it does not work for me, help...

**Comment by raphaieu** [comment]
> I tried everything above and it does not work for me, help...

same problem here... I'm using a Hostinger VPS Ubuntu

**Comment by harisheoran** [comment]
in my case, I used a password to authenticate and yet my SSH password was disabled in sshd configs, so if you are using the private key to SSH, use KEY

**Comment by waqasraza123** [comment]
I had to create key with ed25519 format, then pasted the public key to my ec2 instance and private key to github action secrets and it worked. Using rsa keys with the command `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` did not work for my case.

`ssh-keygen -t ed25519 -a 200 -C "example@gmail.com"`

**Comment by Marcos-MEDENOU** [comment]
> > You only need to authorize your key
> > `cat ~/.ssh/id_rsa.pub >> authorized_key`
> 
> It's funny how something as trivial as this can keep one awake at night! Kuddos! `cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys`

This worked for me
