### ISSUE TITLE
Support for ipv6 ssh connection.

### ISSUE THREAD

**Issue by Hyiker** [appleboy/ssh-action#97]
I tried to run the workflow in my repo with my server(it's ipv6 only, sadly). And I'm expecting this action to add support for ipv6 server, or, to add an optional param to enable ipv6 ssh connection like `ssh -6 xxx@xxxx`.

**Comment by captainyakult** [comment]
was there a resolution to this? I get "dial tcp: address tcp/c23: unknown port" when attempting to use an ipv6 host
